# -*- coding: utf-8 -*-
"""CEPPM_latest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6U5raUID60M4hQmk6KJLnpwA3hNGDdv
"""

# Kiwi Conservation Analysis - EGT and Lotka-Volterra Models
# Complete framework for analyzing kiwi foraging strategies and predator control
#
# CHANGES FROM v1:
# 1. Added logistic growth (carrying capacity K_max) to kiwi equation
# 2. Added Holling Type II functional response (predator saturation)
#
# CHANGES FROM v1 (v2):
# 3. CENTRALISED INITIAL CONDITIONS — all starting values set in one config block
#    at the top of the script; no hardcoded values elsewhere
# 4. LITERATURE-ALIGNED initial conditions (see justification in config block)
# 5. USER-INPUTTED HARVEST RATE — prompted at runtime; scenario comparison
#    across multiple rates also retained so both approaches are available
#
# CHANGES FROM v2 (this version):
# 6. GENERALIST PREDATOR STOAT EQUATION — stoats now have an independent
#    logistic growth term driven by non-kiwi prey (rodents, invertebrates).
#    Previously stoat growth depended entirely on kiwi, causing stoats to
#    decline whenever kiwi declined — ecologically wrong for a generalist.
#    New stoat equation:
#      dS/dt = r_stoat·S·(1 - S/S_max) + β·f(K)·S - δ·S - h·S
#    where r_stoat = baseline growth from non-kiwi prey
#          S_max   = stoat carrying capacity set by broader prey base
#    Kiwi predation now provides a bonus on top of baseline stoat dynamics,
#    consistent with Murphy & Dowding (1995): kiwi <5% of stoat diet.

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.optimize import fsolve
from scipy.integrate import odeint, solve_ivp
from scipy.stats import norm, t, chi2
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D

plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

print("="*70)
print("KIWI CONSERVATION ANALYSIS")
print("Evolutionary Game Theory & Lotka-Volterra Population Dynamics")
print("="*70)

# ============================================================================
# CONFIGURATION BLOCK — ALL INITIAL CONDITIONS AND RUNTIME SETTINGS
# ============================================================================
# Edit values here. Nothing below this block should need to be changed
# for routine scenario testing.

# --- INITIAL POPULATION CONDITIONS ---
# Representing a managed sanctuary unit of ~1,000 ha

K0 = 20       # Initial kiwi population
              # Justification: declining population at roughly 20 birds/1,000 ha
              # Consistent with DOC baseline of ~2% annual decline
              # (DOC Kiwi Recovery Plan 2018-2028)

S0 = 3        # Initial stoat population
              # Justification: ~2-5 stoats/1,000 ha is the ecologically
              # relevant range; 2 stoats/1,000 ha is the maximum tolerable
              # level for successful kiwi juvenile recruitment
              # (Arthur's Pass Wildlife Trust; King & Powell 2007)
              # Female home range ~124 ha, male ~206 ha (Murphy & Dowding 1994)
              # so 3-5 stoats/1,000 ha is a realistic starting density
              # before predator control

X0 = 0.3      # Initial proportion of kiwi using open foraging strategy (EGT)
              # Justification: reflects a population under predation pressure
              # where cover foraging is favoured; 30% open foraging is a
              # conservative starting assumption

# --- HYBRID MODEL USES SAME K0 AND S0 FOR CONSISTENCY ---
# (previously used K0=100, S0=20 — now aligned with L-V model)

# --- SIMULATION SETTINGS ---
DEFAULT_T_MAX = 100   # Simulation duration (years)

try:
    tmax_input = input(
        "\nEnter simulation duration in years "
        "(e.g. 100 for standard run, 300 to show full equilibrium convergence)\n"
        f"  Press Enter to use default ({DEFAULT_T_MAX}): "
    ).strip()
    T_MAX = int(tmax_input) if tmax_input else DEFAULT_T_MAX
    if T_MAX < 10:
        raise ValueError
    print(f"  → Simulation duration: {T_MAX} years")
except (ValueError, EOFError):
    T_MAX = DEFAULT_T_MAX
    print(f"  → Using default simulation duration: {T_MAX} years")

DEFAULT_INTERVENTION_TIME = 20  # default intervention year

try:
    it_input = input(
        "\nEnter the year at which predator control begins "
        f"(1 to {T_MAX - 1})\n"
        "  Guidance: 2=immediate management, 20=delayed start, 50=late intervention\n"
        f"  Press Enter to use default ({DEFAULT_INTERVENTION_TIME}): "
    ).strip()
    INTERVENTION_TIME = int(it_input) if it_input else DEFAULT_INTERVENTION_TIME
    if not 1 <= INTERVENTION_TIME < T_MAX:
        raise ValueError
    print(f"  → Intervention starts at year: {INTERVENTION_TIME}")
except (ValueError, EOFError):
    INTERVENTION_TIME = DEFAULT_INTERVENTION_TIME
    print(f"  → Using default intervention year: {INTERVENTION_TIME}")

# --- USER-INPUTTED HARVEST RATE ---
# The harvest rate is the annual proportion of stoats removed by predator
# control (trapping, 1080, etc.)
#
# Literature reference points:
#   ~0.20 : low-intensity trapping (Murchison Mountains programme,
#            1 trap/21 ha; Tansell et al. via Predator Free NZ Trust 2024)
#   ~0.40 : moderate 1080 aerial operation (DOC National Predator Control
#            Programme; first-season chick survival 50%)
#   ~0.60 : high-intensity combined trapping + 1080
#            (sanctuary-level operations; Germano et al. 2015)
#
# FLOOR AND ERADICATION THRESHOLDS (with current parameters):
#   S_floor    = S_max*(1 - delta/r_stoat) = 8*(1-0.35/0.60) = 3.333
#   h_crit     = r_stoat - delta = 0.60 - 0.35 = 0.25
#     h < 0.25 : stoats sustained by non-kiwi prey at S*(h) > 0
#     h = 0.25 : non-kiwi stoat equilibrium collapses to zero; stoats persist
#                through kiwi predation bonus β·f(K*)·S as kiwi recover
#   h_erad     = r_stoat - delta + β·f(K_max) ≈ 0.32
#     h < 0.32 : stoats persist at positive coexistence equilibrium through
#                kiwi predation bonus (even above h_crit)
#     h ≥ 0.32 : stoat nullcline non-positive across full kiwi density range;
#                stoats driven to zero regardless of kiwi abundance
#   h_erad_theoretical = r_stoat = 0.60
#     theoretical upper bound — harvest exceeds total stoat intrinsic growth
#     capacity; consistent with Predator Free 2050 goal under worst-case
#     mast conditions
#   NOTE: with delta=0.35 (natural mortality, annual survival ~70%), there is
#   NO stable coexistence equilibrium without management — kiwi decline toward
#   local extinction. This correctly reproduces observed field reality
#   (McLennan et al. 1996; DOC Recovery Plan 2018).
#
# If running interactively, the user is prompted below.
# If running non-interactively (e.g. batch), DEFAULT_HARVEST_RATE is used.

DEFAULT_HARVEST_RATE = 0.4   # fallback if no user input

try:
    user_input = input(
        "\nEnter stoat harvest rate for intervention scenario "
        "(0.0 to 1.0; e.g. 0.4 for 40% annual removal)\n"
        "  Guidance: 0.2=low trapping, 0.4=aerial 1080, 0.6=intensive combined\n"
        "  Press Enter to use default (0.4): "
    ).strip()
    HARVEST_RATE = float(user_input) if user_input else DEFAULT_HARVEST_RATE
    if not 0.0 <= HARVEST_RATE <= 1.0:
        raise ValueError
    print(f"  → Using harvest rate: {HARVEST_RATE:.2f}")
except (ValueError, EOFError):
    HARVEST_RATE = DEFAULT_HARVEST_RATE
    print(f"  → Using default harvest rate: {HARVEST_RATE:.2f}")

# --- STOAT GENERALIST PARAMETERS (NEW v3) ---
# Stoats are generalist predators; kiwi represent <5% of their diet
# (Murphy & Dowding 1995). These parameters set the stoat baseline
# dynamics independent of kiwi abundance.

R_STOAT = 0.60  # Stoat intrinsic growth rate from non-kiwi prey
                # Consistent with Barlow & Barron (2005) fitted r_m for
                # non-beech podocarp/broadleaf forest (~0.50-0.80), where
                # prey availability is more stable year-round than beech forest.
                # With delta=0.35 (natural mortality), h_crit=0.25 meaning
                # 25% annual harvest is required to begin suppressing stoats —
                # consistent with NZ management experience that 1080 operations
                # achieving 40-60% knockdown are needed for kiwi recovery
                # (DOC 2024; Germano et al. 2015).
                # Condition required: r_stoat > δ (0.60 > 0.35 ✓)

S_MAX = 8       # Stoat resource ceiling from non-kiwi prey (~1,000 ha)
                #
                # S_floor = S_max*(1 - delta/r_stoat) = 8*(1-0.35/0.60) = 3.333
                #
                # PARAMETERISATION NOTE:
                # S_max=5 (S_floor=2.083) is retained for analytical tractability.
                # Higher values (S_max=8 → S_floor=3.333; S_max=12 → S_floor=5.0)
                # were tested but eliminated interior coexistence equilibria because
                # the stoat nullcline (at ~S_floor) sits too far above the kiwi
                # nullcline (~1.0-1.1) for the nullclines to intersect. Without
                # coexistence equilibria, sensitivity analysis is not possible.
                #
                # S_max=5 represents a conservative managed-sanctuary baseline
                # rather than unmanaged non-mast mainland density (~5-8/1,000 ha).
                # The coexistence regime in the model corresponds to a partially
                # managed state. This is acknowledged as a model limitation.
                #
                # Initialisation note: S0=3 > S_floor=2.083, so stoats decline
                # slightly at the start of the unmanaged simulation before settling
                # at S_floor. This is a known artefact documented in Section 4.4.
                #
                # h_crit = r_stoat - delta = 0.25 (unchanged)
                # h_erad = r_stoat = 0.60 (unchanged)

# --- PHASE PORTRAIT SAMPLE TRAJECTORIES ---
# Starting points for the direction-field plot.
# Kept consistent with K0/S0 range for visual coherence.
PHASE_PORTRAIT_ICS = [
    [K0,      S0],        # baseline start
    [K0 * 2,  S0],        # higher kiwi, same stoats
    [K0,      S0 * 2],    # same kiwi, more stoats
    [K0 * 2,  S0 * 2],    # both higher
]

print("\n" + "="*70)
print("INITIAL CONDITIONS (literature-aligned)")
print("="*70)
print(f"  K0 (kiwi)         = {K0}  birds per ~1,000 ha managed area")
print(f"  S0 (stoats)       = {S0}  stoats per ~1,000 ha")
print(f"  X0 (open forage)  = {X0}  proportion")
print(f"  r_stoat           = {R_STOAT}  (stoat baseline growth from non-kiwi prey)")
print(f"  S_max             = {S_MAX}   (stoat carrying capacity from non-kiwi prey)")
print(f"  Harvest rate      = {HARVEST_RATE}")
print(f"  Intervention at   = year {INTERVENTION_TIME}")
print(f"  Simulation length = {T_MAX} years")# ============================================================================
# DATA SOURCES AND CITATIONS
# ============================================================================

CITATIONS = """
DATA SOURCES:
-------------
1. DOC Kiwi Recovery Plan 2018-2028 (Threatened Species Recovery Plan 64)
2. Save the Kiwi (2024). Population monitoring and research data.
3. DOC National Predator Control Programme (2019 / 2024)
4. McLennan et al. (1996). Role of predation in the decline of kiwi.
   New Zealand Journal of Ecology, 20(1), 27-35.
5. King, C.M. & Powell, R.A. (2007). The Natural History of Weasels and Stoats.
   Oxford University Press.
6. Murphy, E.C. & Dowding, J.E. (1994). Range and diet of stoats in beech forest.
   New Zealand Journal of Ecology, 18(1), 11-18.
7. Arthur's Pass Wildlife Trust. Stoat ecology and density thresholds.
   https://www.apwt.org.nz
8. Tansell et al. (via Predator Free NZ Trust, 2024). Murchison Mountains
   low-intensity trapping programme outcomes.
9. Germano et al. (2015). Mitigation-driven translocations.
   Frontiers in Ecology and the Environment, 13(2), 100-105.

INITIAL CONDITION JUSTIFICATION:
----------------------------------
K0=20: DOC baseline of ~2% annual decline; ~20 birds/1,000 ha is consistent
       with a managed area in early decline before intervention.
S0=3:  2 stoats/1,000 ha = maximum tolerable for kiwi chick recruitment
       (Arthur's Pass Wildlife Trust). Female home range ~124 ha, male ~206 ha
       (Murphy & Dowding 1994), so 3-5 stoats/1,000 ha is realistic before control.
X0=0.3: Conservative assumption; predation pressure favours cover foraging.

GENERALIST STOAT PARAMETERS (updated v4):
------------------------------------------
r_stoat=0.6: Stoat baseline growth from non-kiwi prey. Must exceed δ=0.35
             for stoats to persist independently of kiwi. High fecundity
             (litters 4-12 kits; King & Powell 2007) supports this value.
             Represents a rodent-rich non-mast environment.
S_max=8:     Stoat resource ceiling from non-kiwi prey per 1,000 ha.
             S_floor = 5*(1-0.35/0.60) = 2.083 stoats/1,000 ha.
             Retained at 5 for analytical tractability — higher values
             (8, 12) eliminate interior coexistence equilibria because
             the stoat nullcline sits too far above the kiwi nullcline.
             Represents a conservative managed-sanctuary baseline.
             Acknowledged as a limitation in Section 4.4.
             Coexistence equilibrium: none without management (kiwi decline
             to extinction — correct, consistent with McLennan et al. 1996).
"""
print(CITATIONS)

# ============================================================================
# PART 1: EVOLUTIONARY GAME THEORY MODEL
# ============================================================================

class KiwiEGTModel:
    """
    EGT model for kiwi foraging strategies.
    Strategy A: Open foraging (higher food intake, higher predation risk)
    Strategy B: Cover foraging (lower food intake, lower predation risk)
    """

    def __init__(self, payoff_matrix):
        self.payoff_matrix = np.array(payoff_matrix)

    def payoff_A(self, x):
        a, b = self.payoff_matrix[0]
        return x * a + (1 - x) * b

    def payoff_B(self, x):
        c, d = self.payoff_matrix[1]
        return x * c + (1 - x) * d

    def average_payoff(self, x):
        return x * self.payoff_A(x) + (1 - x) * self.payoff_B(x)

    def replicator_dynamics(self, x, t):
        if x <= 0 or x >= 1:
            return 0
        return x * (self.payoff_A(x) - self.average_payoff(x))

    def find_equilibrium(self):
        a, b, c, d = self.payoff_matrix.flatten()
        denominator = (a - b) + (d - c)
        if abs(denominator) < 1e-10:
            return None
        x_star = (d - b) / denominator
        if 0 <= x_star <= 1:
            return x_star
        return 1.0 if self.payoff_A(1) > self.payoff_B(1) else 0.0

    def stability_analysis(self, x_star):
        h = 1e-8
        derivative = (self.replicator_dynamics(x_star + h, 0) -
                     self.replicator_dynamics(x_star - h, 0)) / (2 * h)
        return f"Stable; derivative = {derivative:.6f}" if derivative < 0 \
               else f"Unstable; derivative = {derivative:.6f}"

    def simulate_dynamics(self, x0, t_max, intervention_time=None, new_payoffs=None):
        t_span = np.linspace(0, t_max, 500)
        if intervention_time is None or intervention_time >= t_max:
            solution = odeint(self.replicator_dynamics, x0, t_span)
            return t_span, solution.flatten()

        t_before = t_span[t_span < intervention_time]
        t_after  = t_span[t_span >= intervention_time]
        sol_before = odeint(self.replicator_dynamics, x0, t_before)

        old_payoffs = self.payoff_matrix.copy()
        self.payoff_matrix = new_payoffs
        x_at = sol_before[-1] if len(sol_before) > 0 else x0
        sol_after = odeint(self.replicator_dynamics, x_at, t_after - intervention_time)
        self.payoff_matrix = old_payoffs

        return np.concatenate([t_before, t_after]), \
               np.concatenate([sol_before.flatten(), sol_after.flatten()])

    def plot_phase_portrait(self):
        x_range = np.linspace(0.01, 0.99, 100)
        dx_dt = [self.replicator_dynamics(x, 0) for x in x_range]
        plt.figure(figsize=(10, 6))
        plt.plot(x_range, dx_dt, 'b-', linewidth=2)
        plt.axhline(y=0, color='k', linestyle='--', alpha=0.5)
        eq = self.find_equilibrium()
        if eq is not None and 0 < eq < 1:
            plt.axvline(x=eq, color='r', linestyle='--', alpha=0.7, linewidth=2,
                       label=f'Equilibrium: {eq:.3f}')
            plt.text(eq, max(dx_dt)*0.8, self.stability_analysis(eq),
                    ha='center', fontsize=10, color='red')
        plt.xlabel('Proportion using Open Foraging', fontsize=12)
        plt.ylabel('Rate of change (dx/dt)', fontsize=12)
        plt.title('Kiwi Foraging Strategy Dynamics - Phase Portrait', fontsize=14)
        plt.legend(fontsize=11)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

    def plot_payoff_functions(self):
        x_range = np.linspace(0, 1, 100)
        plt.figure(figsize=(10, 6))
        plt.plot(x_range, [self.payoff_A(x) for x in x_range], 'b-',
                label='Open Foraging (A)', linewidth=2)
        plt.plot(x_range, [self.payoff_B(x) for x in x_range], 'r-',
                label='Cover Foraging (B)', linewidth=2)
        plt.plot(x_range, [self.average_payoff(x) for x in x_range], 'g--',
                label='Population Average', linewidth=2)
        eq = self.find_equilibrium()
        if eq is not None and 0 < eq < 1:
            plt.axvline(x=eq, color='purple', linestyle=':', alpha=0.7, linewidth=2)
            plt.plot(eq, self.average_payoff(eq), 'ro', markersize=10,
                    label=f'Equilibrium (x={eq:.3f})')
        plt.xlabel('Proportion using Open Foraging', fontsize=12)
        plt.ylabel('Expected Payoff (offspring per year)', fontsize=12)
        plt.title('Kiwi Foraging Strategy Payoffs', fontsize=14)
        plt.legend(fontsize=11)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()


# ============================================================================
# PART 2: LOTKA-VOLTERRA PREDATOR-PREY MODEL (EXTENDED)
# ============================================================================

class KiwiLotkaVolterraModel:
    """
    Extended Lotka-Volterra model with:
    1. Logistic prey growth:       dK/dt = rK(1 - K/K_max) - f(K)·S
    2. Holling Type II predation:  f(K) = αK / (1 + αhK)
    3. Generalist stoat equation:  dS/dt = r_stoat·S·(1 - S/S_max)
                                          + β·f(K)·S - δ·S - h·S

    Extension 3 (new in v3):
    ─────────────────────────
    Previously stoat growth depended solely on kiwi consumption (β·f(K)·S),
    meaning stoats declined whenever kiwi declined. This is ecologically
    incorrect: stoats are generalist predators for whom kiwi represent less
    than 5% of diet (Murphy & Dowding 1995). The new term r_stoat·S·(1-S/S_max)
    gives stoats an independent logistic growth from their broader prey base
    (rodents, invertebrates). Kiwi predation adds on top of this baseline.

    Biological interpretation:
      r_stoat : stoat intrinsic growth rate from non-kiwi prey
      S_max   : stoat carrying capacity supported by non-kiwi prey alone
    When kiwi are scarce, stoats persist at S_max (set by rodent availability).
    When kiwi are abundant, stoat population can exceed S_max temporarily.
    """

    def __init__(self, r, alpha, beta, delta, K_max=150, h=0.1,
                 r_stoat=0.3, S_max=10):
        self.r       = r
        self.alpha   = alpha
        self.beta    = beta
        self.delta   = delta
        self.K_max   = K_max
        self.h       = h
        self.r_stoat = r_stoat  # NEW: stoat baseline growth from non-kiwi prey
        self.S_max   = S_max    # NEW: stoat carrying capacity from non-kiwi prey

    def predation_rate(self, K):
        return (self.alpha * K) / (1 + self.alpha * self.h * K)

    def system_equations(self, t, y, harvest_rate=0):
        """
        Kiwi:  dK/dt = rK(1 - K/K_max) - f(K)·S
        Stoat: dS/dt = r_stoat·S·(1-S/S_max) + β·f(K)·S - δ·S - h·S

        ORIGINAL FORMULATION (restored from Option A):
        ───────────────────────────────────────────────
        r_stoat and delta are kept SEPARATE in the logistic term so their
        biological distinction is preserved in the code. The observable
        stoat equilibrium without management is:

            S_floor = S_max × (1 - δ/r_stoat) = 12 × (1 - 0.35/0.60) = 5.0

        S_max = 12 is a latent resource ceiling (not directly observable).
        S_floor = 5.0 is the directly observable non-mast equilibrium density,
        matching Murphy & Dowding (1994, 1995): 5-8 stoats/1,000 ha.

        S₀ = 3 < S_floor = 5 → stoats correctly increase toward 5 in the
        unmanaged baseline.

        The floor logic is restored: floor enforcement prevents stoats
        declining below S_floor due to kiwi scarcity alone (non-kiwi prey
        always sustains them at S_floor). Harvest bypasses the floor entirely.

        Three regimes:
          h = 0             : stoats settle at S_floor from non-kiwi prey
          0 < h < h_crit    : stoats suppressed; kiwi may recover
          h >= h_crit=0.25  : net stoat decline — eradication possible
        """
        K, S = y
        K = max(K, 0)
        S = max(S, 0)
        f_K = self.predation_rate(K)

        dKdt = self.r * K * (1 - K / self.K_max) - f_K * S

        natural_dSdt = (self.r_stoat * S * (1 - S / self.S_max)
                        + self.beta * f_K * S
                        - self.delta * S)

        # Floor enforcement — prevents stoats declining below S_floor
        # due to kiwi scarcity. Non-kiwi prey sustains stoats at S_floor.
        # Harvest bypasses floor entirely.
        S_floor = self.S_max * (1 - self.delta / self.r_stoat)
        non_kiwi_growth = self.r_stoat * S * (1 - S / self.S_max) - self.delta * S
        if S <= S_floor and non_kiwi_growth < 0:
            natural_dSdt = max(natural_dSdt, 0.0)

        harvest_dSdt = -harvest_rate * S
        dSdt = natural_dSdt + harvest_dSdt

        return [dKdt, dSdt]

    def find_equilibrium(self, harvest_rate=0, suppress_warnings=False):
        """
        Numerical equilibrium finder (original formulation restored).

        Four possible outcomes based on nullcline analysis:
        ────────────────────────────────────────────────
        1. COEXISTENCE equilibrium (K>0, S>0): found numerically where both
           nullclines intersect. Exists in partial recovery zone (h < h_crit)
           and kiwi bonus zone (h_crit < h < h_erad).

        2. KIWI BONUS ZONE (h_crit < h < h_erad ≈ 0.32):
           Non-kiwi stoat equilibrium S*(h) < 0 but stoats persist at a
           reduced positive equilibrium through the kiwi predation bonus
           β·f(K)·S as kiwi recover under predator control. The numerical
           solver above should find this intersection; this fallback applies
           if it does not converge.
           h_crit  = r_stoat - delta = 0.25
           h_erad  = r_stoat - delta + β·f(K_max) ≈ 0.32

        3. FULL SUPPRESSION (h_erad ≤ h < r_stoat): stoat nullcline
           non-positive across full kiwi density range; stoats driven to
           zero; kiwi recover to K_max.

        4. THEORETICAL UPPER BOUND (h ≥ r_stoat = 0.60): harvest exceeds
           total stoat intrinsic growth capacity; PF2050 scenario.
        """
        S_floor  = self.S_max * (1 - self.delta / self.r_stoat)
        h_crit   = self.r_stoat - self.delta
        f_Kmax   = (self.alpha * self.K_max
                    / (1 + self.alpha * self.h * self.K_max))
        h_erad   = h_crit + self.beta * f_Kmax   # ≈ 0.320

        def equations(vars):
            K, S = vars
            K = max(K, 1e-6)
            S = max(S, 1e-6)
            f_K  = self.predation_rate(K)
            eq1  = self.r * K * (1 - K / self.K_max) - f_K * S
            eq2  = (self.r_stoat * S * (1 - S / self.S_max)
                    + self.beta * f_K * S
                    - self.delta * S
                    - harvest_rate * S)
            return [eq1, eq2]

        # Extend initial guesses to cover kiwi bonus zone (S near zero, K large)
        best = None
        best_residual = np.inf
        K_guesses = [10, 20, 30, 50, 80, 100, 120, 140]
        S_guesses = [0.05, 0.1, 0.3, 0.5, 1.0, 2.0, 3.0, 4.0]
        for K_g in K_guesses:
            for S_g in S_guesses:
                try:
                    sol = fsolve(equations, [K_g, S_g], full_output=True)
                    K_eq, S_eq = sol[0]
                    residual = max(abs(x) for x in equations(sol[0]))
                    if (K_eq > 1 and S_eq > 1e-4
                            and K_eq < self.K_max
                            and residual < 1e-6):
                        if residual < best_residual:
                            best = (K_eq, S_eq)
                            best_residual = residual
                except:
                    pass

        if best is not None:
            return best[0], best[1]

        # No coexistence found — determine regime from nullcline analysis
        if harvest_rate >= h_erad:
            # Full suppression or theoretical upper bound —
            # stoat nullcline non-positive everywhere; stoats eradicated
            return self.K_max, 0.0
        elif harvest_rate > h_crit:
            # Kiwi bonus zone — numerical solver failed to find intersection;
            # return approximate kiwi bonus equilibrium as fallback
            # (S small positive, K large but < K_max)
            if not suppress_warnings:
                print(f"  NOTE: kiwi bonus zone (h={harvest_rate:.2f}, "
                      f"h_crit={h_crit:.2f}, h_erad={h_erad:.3f}) — "
                      f"numerical solver did not converge; returning approximation.")
            return self.K_max * 0.95, 0.05
        else:
            if not suppress_warnings:
                print(f"  NOTE: no coexistence equilibrium (h={harvest_rate:.2f}, "
                      f"h_crit={h_crit:.2f}). Kiwi decline toward extinction.")
            return 0.0, S_floor

    def simulate_dynamics(self, initial_conditions, t_max,
                         intervention_time=None, harvest_rate=0):
        """Uses K0, S0 from initial_conditions argument (set from config block)."""
        K0_sim, S0_sim = initial_conditions

        if intervention_time is None or intervention_time >= t_max:
            t_eval = np.linspace(0, t_max, 1000)
            sol = solve_ivp(lambda t, y: self.system_equations(t, y, 0),
                           [0, t_max], [K0_sim, S0_sim],
                           t_eval=t_eval, method='RK45')
            return sol.t, sol.y[0], sol.y[1]

        t_before = np.linspace(0, intervention_time, 500)
        t_after  = np.linspace(intervention_time, t_max, 500)

        sol_b = solve_ivp(lambda t, y: self.system_equations(t, y, 0),
                         [0, intervention_time], [K0_sim, S0_sim],
                         t_eval=t_before, method='RK45')

        sol_a = solve_ivp(lambda t, y: self.system_equations(t, y, harvest_rate),
                         [intervention_time, t_max],
                         [sol_b.y[0][-1], sol_b.y[1][-1]],
                         t_eval=t_after, method='RK45')

        return (np.concatenate([sol_b.t,    sol_a.t]),
                np.concatenate([sol_b.y[0], sol_a.y[0]]),
                np.concatenate([sol_b.y[1], sol_a.y[1]]))

    def plot_time_series(self, times, kiwi, stoats,
                        intervention_time=None, harvest_rate=None):
        fig, axes = plt.subplots(2, 1, figsize=(12, 9))
        S_floor = self.S_max * (1 - self.delta / self.r_stoat)

        # ── Top panel: dual y-axis time series ──
        ax_k = axes[0]
        ax_s = ax_k.twinx()

        ln1, = ax_k.plot(times, kiwi,  'b-', linewidth=2, label='Kiwi population')
        ln2, = ax_s.plot(times, stoats, 'r-', linewidth=2, label='Stoat population')
        ln3  = ax_k.axhline(y=self.K_max, color='blue', linestyle=':', alpha=0.5,
                             linewidth=1.5, label=f'Kiwi K_max = {self.K_max}')
        ln4  = ax_s.axhline(y=S_floor, color='red', linestyle='--', alpha=0.6,
                             linewidth=1.5,
                             label=f'Stoat S_floor = {S_floor:.1f} (non-kiwi equil.)')

        if intervention_time:
            label = (f'Predator control starts (h={harvest_rate:.2f})'
                     if harvest_rate else 'Predator control starts')
            ax_k.axvline(x=intervention_time, color='green', linestyle='--',
                        alpha=0.7, linewidth=2, label=label)

        ax_k.set_xlabel('Time (years)', fontsize=12)
        ax_k.set_ylabel('Kiwi population', color='blue', fontsize=12)
        ax_s.set_ylabel('Stoat population', color='red',  fontsize=12)
        ax_k.tick_params(axis='y', labelcolor='blue')
        ax_s.tick_params(axis='y', labelcolor='red')
        ax_s.set_ylim(0, self.S_max * 1.4)

        lines  = [ln1, ln2, ln3, ln4]
        if intervention_time:
            from matplotlib.lines import Line2D
            lines.append(Line2D([0], [0], color='green', linestyle='--',
                                linewidth=2, label=label))
        ax_k.legend(lines, [l.get_label() for l in lines], fontsize=10,
                    loc='upper right')

        ax_k.set_title('Kiwi-Stoat Population Dynamics\n'
                       '(Logistic Growth + Holling Type II + Generalist Stoat)\n'
                       'No management = kiwi extinction trajectory',
                       fontsize=13)
        ax_k.grid(True, alpha=0.3)

        # ── Bottom panel: phase portrait ──
        ax = axes[1]
        ax.plot(kiwi, stoats, 'purple', linewidth=2, alpha=0.8)
        ax.plot(kiwi[0],  stoats[0],  'go', markersize=10, label='Start')
        ax.plot(kiwi[-1], stoats[-1], 'rs', markersize=10, label='End')
        K_eq, S_eq = self.find_equilibrium(0)
        ax.plot(K_eq, S_eq, 'ko', markersize=8,
               label=f'Coexistence equilibrium: K={K_eq:.1f}, S={S_eq:.1f}')
        ax.axhline(y=S_floor, color='red', linestyle='--', alpha=0.5,
                  label=f'Stoat S_floor = {S_floor:.1f} (non-kiwi equil.)')
        ax.set_xlabel('Kiwi population', fontsize=12)
        ax.set_ylabel('Stoat population', fontsize=12)
        ax.set_title('Phase Portrait', fontsize=14)
        ax.legend(fontsize=11)
        ax.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    def plot_stoat_persistence(self):
        """
        Demonstrates three stoat regimes under the floor logic:
          1. No harvest      : stoats settle at S_floor from non-kiwi prey
          2. Moderate harvest: stoats suppressed; floor partially holds
          3. Intensive harvest: eradication — stoats driven to zero
        """
        t_eval  = np.linspace(0, T_MAX, 1000)
        S_floor = self.S_max * (1 - self.delta / self.r_stoat)
        h_crit  = self.r_stoat - self.delta

        def no_kiwi_stoats(t, y):
            S = max(y[0], 0)
            natural = self.r_stoat * S * (1 - S / self.S_max) - self.delta * S
            if S <= S_floor and natural < 0:
                natural = 0.0
            return [natural]
        sol_nokiwi = solve_ivp(no_kiwi_stoats, [0, T_MAX], [S0],
                               t_eval=t_eval, method='RK45')

        def moderate_harvest(t, y):
            S = max(y[0], 0)
            natural = self.r_stoat * S * (1 - S / self.S_max) - self.delta * S
            if S <= S_floor and natural < 0:
                natural = 0.0
            return [natural - 0.4 * S]
        sol_mod = solve_ivp(moderate_harvest, [0, T_MAX], [S0],
                            t_eval=t_eval, method='RK45')

        def intensive_harvest(t, y):
            S = max(y[0], 0)
            natural = self.r_stoat * S * (1 - S / self.S_max) - self.delta * S
            if S <= S_floor and natural < 0:
                natural = 0.0
            return [natural - 0.8 * S]
        sol_erad = solve_ivp(intensive_harvest, [0, T_MAX], [S0],
                             t_eval=t_eval, method='RK45')

        sol_normal = solve_ivp(
            lambda t, y: self.system_equations(t, y, 0),
            [0, T_MAX], [K0, S0], t_eval=t_eval, method='RK45'
        )

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        ax = axes[0]
        ax.plot(sol_normal.t, sol_normal.y[1], 'b-',  linewidth=2,
               label='No harvest (kiwi present)')
        ax.plot(sol_nokiwi.t, sol_nokiwi.y[0], 'g--', linewidth=2,
               label='No harvest (kiwi absent — non-kiwi prey only)')
        ax.plot(sol_mod.t,    sol_mod.y[0],    'orange', linewidth=2,
               linestyle='--', label=f'Moderate harvest (h=0.4 > h_crit={h_crit:.2f})')
        ax.plot(sol_erad.t,   sol_erad.y[0],   'r-',  linewidth=2,
               label=f'Intensive harvest (h=0.8 > r_stoat={self.r_stoat}) — eradication')
        ax.axhline(y=S_floor, color='gray', linestyle=':', alpha=0.7,
                  label=f'S_floor = {S_floor:.2f} (non-kiwi prey equilibrium)')
        ax.axhline(y=0, color='black', linestyle='-', linewidth=0.8, alpha=0.3)
        ax.set_xlabel('Time (years)', fontsize=12)
        ax.set_ylabel('Stoat population', fontsize=12)
        ax.set_title('Three Stoat Regimes\n'
                    'Floor blocks natural decline only; harvest can eradicate',
                    fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

        ax = axes[1]
        ax.plot(sol_normal.y[0], sol_normal.y[1], 'b-', linewidth=2,
               label='No harvest')
        ax.axhline(y=S_floor, color='gray', linestyle=':', alpha=0.7,
                  label=f'S_floor = {S_floor:.2f}')
        ax.axhline(y=0, color='red', linestyle='--', alpha=0.5,
                  label='Eradication (h > r_stoat)')
        K_eq, S_eq = self.find_equilibrium(0)
        ax.plot(K_eq, S_eq, 'ko', markersize=10,
               label=f'Coexistence eq: K={K_eq:.1f}, S={S_eq:.2f}')
        ax.plot(self.K_max, 0, 'r^', markersize=12,
               label=f'Eradication eq: K={self.K_max}, S=0')
        ax.plot(0, S_floor, 'gs', markersize=10,
               label=f'Stoat-only eq: K=0, S={S_floor:.2f}')
        ax.set_xlabel('Kiwi population', fontsize=12)
        ax.set_ylabel('Stoat population', fontsize=12)
        ax.set_title('Three Equilibria\n'
                    'Coexistence / Stoat-only / Eradication', fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

        print(f"\n  Stoat regime thresholds:")
        print(f"    S_floor = S_max*(1-delta/r_stoat) = {S_floor:.3f}")
        print(f"    h_crit  = r_stoat - delta = {h_crit:.3f}")
        print(f"    h_erad  = r_stoat         = {self.r_stoat:.3f}")
        print(f"    h < {h_crit:.2f}  : stoats at S_floor={S_floor:.2f}; kiwi decline")
        print(f"    {h_crit:.2f} < h < {self.r_stoat:.2f}: stoats suppressed; kiwi recover")
        print(f"    h > {self.r_stoat:.2f}  : eradication — stoats driven to zero")

    def plot_phase_portrait_with_field(self, phase_ics):
        """phase_ics: list of [K0, S0] starting points from config block."""
        K_range = np.linspace(0, self.K_max * 1.1, 15)
        S_range = np.linspace(0, max(s for _, s in phase_ics) * 2.5, 15)
        K_grid, S_grid = np.meshgrid(K_range, S_range)
        dK = np.zeros_like(K_grid)
        dS = np.zeros_like(S_grid)
        for i in range(K_grid.shape[0]):
            for j in range(K_grid.shape[1]):
                d = self.system_equations(0, [K_grid[i,j], S_grid[i,j]], 0)
                dK[i,j], dS[i,j] = d

        plt.figure(figsize=(10, 8))
        plt.quiver(K_grid, S_grid, dK, dS, alpha=0.6, color='gray')
        plt.axvline(x=self.K_max, color='blue', linestyle=':', alpha=0.5,
                   linewidth=2, label=f'K_max = {self.K_max}')

        colors = ['blue', 'green', 'orange', 'purple']
        for ic, color in zip(phase_ics, colors):
            t_sim, K_sim, S_sim = self.simulate_dynamics(ic, T_MAX)
            plt.plot(K_sim, S_sim, color=color, linewidth=2, alpha=0.7)
            plt.plot(ic[0], ic[1], 'o', color=color, markersize=8)

        K_eq, S_eq = self.find_equilibrium(0)
        plt.plot(K_eq, S_eq, 'ro', markersize=12,
                label=f'Equilibrium: K={K_eq:.1f}, S={S_eq:.1f}')
        plt.xlabel('Kiwi Population', fontsize=12)
        plt.ylabel('Stoat Population', fontsize=12)
        plt.title('Kiwi-Stoat Phase Portrait with Direction Field\n'
                 '(Logistic Growth + Holling Type II)', fontsize=14)
        plt.legend(fontsize=11)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

    def plot_holling_response(self):
        K_range = np.linspace(0, self.K_max, 200)
        plt.figure(figsize=(10, 5))
        plt.plot(K_range, [self.predation_rate(K) for K in K_range],
                'b-', linewidth=2.5, label='Holling Type II (this model)')
        plt.plot(K_range, [self.alpha * K for K in K_range],
                'r--', linewidth=2, alpha=0.7, label='Standard L-V (linear)')
        plt.axhline(y=1/self.h, color='blue', linestyle=':', alpha=0.5,
                   label=f'Saturation ceiling (1/h = {1/self.h:.1f})')
        plt.xlabel('Kiwi Population (K)', fontsize=12)
        plt.ylabel('Per-stoat predation rate f(K)', fontsize=12)
        plt.title('Holling Type II vs Standard L-V Predation', fontsize=13)
        plt.legend(fontsize=11)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()


# ============================================================================
# PART 3: HYBRID MODEL (EGT + EXTENDED LOTKA-VOLTERRA)
# ============================================================================

class KiwiHybridModel:
    """
    Hybrid model combining EGT strategy dynamics with extended L-V population
    dynamics. Extended in v4 with DYNAMIC PAYOFF FEEDBACK.

    Previous version: payoff matrix was fixed — strategy evolution was
    decoupled from population state, causing open foraging to increase even
    as the population collapsed under predation pressure.

    This version: payoffs are adjusted dynamically based on current stoat
    density S. Higher stoat density penalises open foraging more than cover
    foraging, creating a biologically realistic feedback loop:

        High S → open foraging costly → strategy shifts toward cover
        Low S  → open foraging rewarding → strategy shifts toward open

    Predation penalty scales with stoat density and strategy vulnerability:
        open_penalty  = alpha_base * S * open_vulnerability_factor
        cover_penalty = alpha_base * S * cover_vulnerability_factor

    This ensures the EGT and L-V components respond to the same ecological
    conditions rather than running in parallel without meaningful coupling.
    """

    def __init__(self, egt_model, r_base, alpha_base, beta, delta,
                 K_max=150, h=0.1, r_stoat=0.6, S_max=3):
        self.egt_model    = egt_model
        # Hybrid base payoffs: near-neutral between strategies in the absence
        # of predation pressure. The sigmoid penalty system then tips the
        # balance — cover foraging is favoured when stoats are high (S>1),
        # open foraging is rewarded when stoats are controlled (S<1).
        # Calibrated so the strategy flip point (~S=1.5) is consistent with
        # the literature threshold of ~2 stoats/1,000 ha above which kiwi
        # chick recruitment fails (Arthur's Pass Wildlife Trust).
        self.base_payoffs = np.array([
            [0.35, 0.55],   # Open foraging: moderate reward vs both strategies
            [0.50, 0.22]    # Cover foraging: higher reward when open common,
                            # minimum viable (0.22) when cover common
        ])
        self.r_base       = r_base
        self.alpha_base   = alpha_base
        self.beta         = beta
        self.delta        = delta
        self.K_max        = K_max
        self.h            = h
        self.r_stoat      = r_stoat
        self.S_max        = S_max

    def predation_rate(self, alpha_eff, K):
        return (alpha_eff * K) / (1 + alpha_eff * self.h * K)

    def dynamic_payoffs(self, S):
        """
        Sigmoid predation penalty applied to base payoffs.

        Uses a logistic (sigmoid) function rather than a linear penalty,
        giving a smooth, bounded response to stoat density:

            penalty = max_penalty / (1 + exp(-k * (S - S_mid)))

        Parameters calibrated so that:
          S < 1.0: open foraging favoured (managed, low predation pressure)
          S ~ 1.5: strategies near-equal (transition zone)
          S > 2.0: cover foraging strongly favoured (high predation pressure)

        This flip point (~1.5 stoats/1,000 ha) is consistent with the
        literature threshold above which kiwi chick recruitment fails
        (Arthur's Pass Wildlife Trust; 2 stoats/1,000 ha maximum tolerable).

        Open foraging receives a larger maximum penalty (0.40) than cover
        foraging (0.15), reflecting the 30/70% vulnerability split.
        """
        k        = 3.0    # sigmoid steepness
        S_mid    = 1.0    # inflection point (stoats/1,000 ha)
        open_max = 0.40   # maximum penalty for open foraging
        cov_max  = 0.15   # maximum penalty for cover foraging

        sig      = 1 / (1 + np.exp(-k * (S - S_mid)))
        open_pen = open_max * sig
        cov_pen  = cov_max  * sig

        return np.array([
            [max(self.base_payoffs[0, 0] - open_pen, 0.01),
             max(self.base_payoffs[0, 1] - open_pen, 0.01)],
            [max(self.base_payoffs[1, 0] - cov_pen,  0.01),
             max(self.base_payoffs[1, 1] - cov_pen,  0.01)]
        ])

    def strategy_dependent_parameters(self, x):
        """
        Calculate effective L-V parameters based on current strategy mix.
        Uses base payoffs for the r_effective scaling (population-level effect).
        Dynamic payoffs handle the EGT strategy selection separately.
        """
        open_vulnerability  = 1.3
        cover_vulnerability = 0.7
        avg_vulnerability   = x * open_vulnerability + (1-x) * cover_vulnerability

        # Use base payoffs for average fitness scaling.
        # Normalisation constant PI_BAR_ESS = pi_bar(x*) is the average payoff
        # at the EGT equilibrium x*, computed dynamically from the base payoff
        # matrix so that it updates automatically if payoff values change.
        # At the ESS, pi_A(x*) = pi_B(x*) by definition, so pi_bar(x*) equals
        # the common equilibrium payoff. The ESS is derived from the payoff
        # matrix entries a,b,c,d as: x* = (d-b) / [(a-b) + (d-c)].
        # This ensures r_effective = r_base exactly when x = x*, and scales
        # smoothly below r_base as the population moves away from the ESS.
        a, b = self.base_payoffs[0]
        c, d = self.base_payoffs[1]
        denom = (a - b) + (d - c)
        x_star = (d - b) / denom if abs(denom) > 1e-10 else 0.5
        x_star = float(np.clip(x_star, 0.0, 1.0))
        PI_BAR_ESS       = self.egt_model.average_payoff(x_star)
        avg_reproduction = self.egt_model.average_payoff(x)

        return {
            'r_effective':     self.r_base * (avg_reproduction / PI_BAR_ESS),
            'alpha_effective': self.alpha_base * avg_vulnerability
        }

    def hybrid_system(self, t, y, harvest_rate=0):
        """
        Combined system with dynamic payoff feedback and optional harvest.

        dx/dt uses DYNAMIC payoffs (stoat-density-adjusted) so strategy
        selection responds to current predation pressure.

        dK/dt and dS/dt use strategy-dependent L-V parameters.

        harvest_rate: annual proportion of stoats removed by predator control.
        Uses same floor/harvest separation as KiwiLotkaVolterraModel —
        floor blocks only natural decline; harvest bypasses floor entirely.
        """
        x, K, S = y
        x = np.clip(x, 0.01, 0.99)
        K = max(K, 0)
        S = max(S, 0)

        # --- EGT replicator with dynamic payoffs ---
        dynamic_pm = self.dynamic_payoffs(S)
        self.egt_model.payoff_matrix = dynamic_pm

        pi_A   = self.egt_model.payoff_A(x)
        pi_avg = self.egt_model.average_payoff(x)
        dxdt   = x * (pi_A - pi_avg) if 0 < x < 1 else 0

        self.egt_model.payoff_matrix = self.base_payoffs

        # --- L-V population dynamics ---
        params = self.strategy_dependent_parameters(x)
        f_K    = self.predation_rate(params['alpha_effective'], K)
        dKdt   = params['r_effective'] * K * (1 - K / self.K_max) - f_K * S

        # Original formulation: r_stoat and delta kept separate
        # S_floor = S_max*(1-delta/r_stoat) = 12*(1-0.35/0.60) = 5.0
        natural_dSdt = (self.r_stoat * S * (1 - S / self.S_max)
                        + self.beta * f_K * S
                        - self.delta * S)
        S_floor = self.S_max * (1 - self.delta / self.r_stoat)
        non_kiwi_growth = self.r_stoat * S * (1 - S / self.S_max) - self.delta * S
        if S <= S_floor and non_kiwi_growth < 0:
            natural_dSdt = max(natural_dSdt, 0.0)
        harvest_dSdt = -harvest_rate * S
        dSdt = natural_dSdt + harvest_dSdt

        return [dxdt, dKdt, dSdt]

    def simulate_hybrid_dynamics(self, initial_conditions, t_max,
                                  intervention_time=None, harvest_rate=0):
        """
        Simulate the hybrid model with optional predator control intervention.

        Parameters:
        initial_conditions : [x0, K0, S0] — drawn from config block
        t_max              : simulation duration
        intervention_time  : year at which harvest begins (None = no intervention)
        harvest_rate       : annual stoat removal rate (0 = natural baseline)
        """
        x0, K0_h, S0_h = initial_conditions

        if intervention_time is None or intervention_time >= t_max:
            t_eval = np.linspace(0, t_max, 1000)
            sol    = solve_ivp(
                lambda t, y: self.hybrid_system(t, y, 0),
                [0, t_max], [x0, K0_h, S0_h],
                t_eval=t_eval, method='RK45'
            )
            self.egt_model.payoff_matrix = self.base_payoffs
            return sol.t, sol.y[0], sol.y[1], sol.y[2]

        # Two-phase simulation: before and after intervention
        t_before = np.linspace(0, intervention_time, 400)
        t_after  = np.linspace(intervention_time, t_max, 600)

        sol_b = solve_ivp(
            lambda t, y: self.hybrid_system(t, y, 0),
            [0, intervention_time], [x0, K0_h, S0_h],
            t_eval=t_before, method='RK45'
        )

        sol_a = solve_ivp(
            lambda t, y: self.hybrid_system(t, y, harvest_rate),
            [intervention_time, t_max],
            [sol_b.y[0][-1], sol_b.y[1][-1], sol_b.y[2][-1]],
            t_eval=t_after, method='RK45'
        )

        self.egt_model.payoff_matrix = self.base_payoffs
        return (np.concatenate([sol_b.t,    sol_a.t]),
                np.concatenate([sol_b.y[0], sol_a.y[0]]),
                np.concatenate([sol_b.y[1], sol_a.y[1]]),
                np.concatenate([sol_b.y[2], sol_a.y[2]]))

    def plot_hybrid_results(self, t, x, K, S,
                            t_m=None, x_m=None, K_m=None, S_m=None,
                            intervention_time=None, harvest_rate=None):
        """
        Plot hybrid model results.
        If managed trajectories (t_m, x_m, K_m, S_m) are provided,
        shows baseline vs managed comparison on each panel.
        """
        fig = plt.figure(figsize=(15, 12))
        S_floor = self.S_max * (1 - self.delta / self.r_stoat)
        has_managed = t_m is not None

        def add_managed(ax, t_m, vals_m, color='orange', label='With predator control'):
            if has_managed:
                ax.plot(t_m, vals_m, color=color, linewidth=2,
                       linestyle='--', label=label, alpha=0.85)

        # --- Strategy evolution ---
        ax = fig.add_subplot(2, 3, 1)
        ax.plot(t, x, 'b-', linewidth=2, label='No predator control')
        add_managed(ax, t_m, x_m)
        if intervention_time:
            ax.axvline(x=intervention_time, color='green', linestyle=':',
                      alpha=0.7, linewidth=1.5,
                      label=f'Control starts yr {intervention_time}')
        ax.set_xlabel('Time (years)', fontsize=11)
        ax.set_ylabel('Proportion Open Foraging', fontsize=11)
        ax.set_title('Strategy Evolution\n(Dynamic payoff feedback)', fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)
        ax.set_ylim(0, 1)

        # --- Population dynamics ---
        ax = fig.add_subplot(2, 3, 2)
        ax.plot(t, K, 'g-', linewidth=2, label='Kiwi (no control)')
        ax.plot(t, S, 'r-', linewidth=2, label='Stoats (no control)')
        if has_managed:
            ax.plot(t_m, K_m, 'g--', linewidth=2, alpha=0.85,
                   label='Kiwi (with control)')
            ax.plot(t_m, S_m, 'r--', linewidth=2, alpha=0.85,
                   label='Stoats (with control)')
        ax.axhline(y=self.K_max, color='green', linestyle=':', alpha=0.3,
                  label=f'K_max={self.K_max}')
        ax.axhline(y=self.S_max, color='red', linestyle=':', alpha=0.3,
                  label=f'S_floor={self.S_max*(1-self.delta/self.r_stoat):.1f} (non-kiwi equil.)')
        if intervention_time:
            ax.axvline(x=intervention_time, color='green', linestyle=':',
                      alpha=0.7, linewidth=1.5)
        ax.set_xlabel('Time (years)', fontsize=11)
        ax.set_ylabel('Population Size', fontsize=11)
        ax.set_title('Population Dynamics', fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

        # --- 3D phase space ---
        ax = fig.add_subplot(2, 3, 3, projection='3d')
        ax.plot(x, K, S, 'b-', linewidth=2, alpha=0.8, label='No control')
        ax.scatter(x[0], K[0], S[0], color='green', s=100, label='Start')
        ax.scatter(x[-1], K[-1], S[-1], color='blue', s=100, label='End (no ctrl)')
        if has_managed:
            ax.plot(x_m, K_m, S_m, color='orange', linewidth=2,
                   alpha=0.8, linestyle='--', label='With control')
            ax.scatter(x_m[-1], K_m[-1], S_m[-1], color='orange',
                      s=100, marker='s', label='End (managed)')
        ax.set_xlabel('Strategy (x)', fontsize=10)
        ax.set_ylabel('Kiwi (K)', fontsize=10)
        ax.set_zlabel('Stoats (S)', fontsize=10)
        ax.set_title('3D Phase Space', fontsize=12)
        ax.legend(fontsize=8)

        # --- Dynamic payoff advantage ---
        ax = fig.add_subplot(2, 3, 4)
        x_range = np.linspace(0.01, 0.99, 100)
        s_levels  = [0.5, 1.0, 2.0, 3.0]
        colors_p  = ['green', 'blue', 'orange', 'red']
        for s_val, col in zip(s_levels, colors_p):
            dp = self.dynamic_payoffs(s_val)
            tmp = KiwiEGTModel(dp)
            diff = [tmp.payoff_A(xi) - tmp.payoff_B(xi) for xi in x_range]
            ax.plot(x_range, diff, color=col, linewidth=2, label=f'S={s_val}')
        ax.axhline(y=0, color='black', linestyle='--', alpha=0.5)
        ax.set_xlabel('Proportion Open Foraging (x)', fontsize=11)
        ax.set_ylabel('π_A − π_B  (open advantage)', fontsize=11)
        ax.set_title('Dynamic Payoff Advantage\nby Stoat Density', fontsize=12)
        ax.legend(fontsize=10, title='Stoat density')
        ax.grid(True, alpha=0.3)

        # --- Effective parameters ---
        ax = fig.add_subplot(2, 3, 5)
        r_vals = [self.strategy_dependent_parameters(xi)['r_effective'] for xi in x]
        a_vals = [self.strategy_dependent_parameters(xi)['alpha_effective'] for xi in x]
        ax.plot(t, r_vals, 'b-', label='r_eff (no ctrl)', linewidth=2)
        ax.plot(t, a_vals, 'r-', label='α_eff (no ctrl)', linewidth=2)
        if has_managed:
            r_m = [self.strategy_dependent_parameters(xi)['r_effective'] for xi in x_m]
            a_m = [self.strategy_dependent_parameters(xi)['alpha_effective'] for xi in x_m]
            ax.plot(t_m, r_m, 'b--', label='r_eff (managed)', linewidth=2, alpha=0.7)
            ax.plot(t_m, a_m, 'r--', label='α_eff (managed)', linewidth=2, alpha=0.7)
        if intervention_time:
            ax.axvline(x=intervention_time, color='green', linestyle=':',
                      alpha=0.7, linewidth=1.5)
        ax.set_xlabel('Time (years)', fontsize=11)
        ax.set_ylabel('Parameter Value', fontsize=11)
        ax.set_title('Strategy-Dependent Parameters', fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

        # --- Average fitness ---
        ax = fig.add_subplot(2, 3, 6)
        fitness = []
        for i in range(len(t)):
            dp = self.dynamic_payoffs(S[i])
            self.egt_model.payoff_matrix = dp
            fitness.append(self.egt_model.average_payoff(x[i]))
        self.egt_model.payoff_matrix = self.base_payoffs
        ax.plot(t, fitness, 'g-', linewidth=2, label='No control')
        if has_managed:
            fitness_m = []
            for i in range(len(t_m)):
                dp = self.dynamic_payoffs(S_m[i])
                self.egt_model.payoff_matrix = dp
                fitness_m.append(self.egt_model.average_payoff(x_m[i]))
            self.egt_model.payoff_matrix = self.base_payoffs
            ax.plot(t_m, fitness_m, 'g--', linewidth=2,
                   alpha=0.85, label='With control')
        if intervention_time:
            ax.axvline(x=intervention_time, color='green', linestyle=':',
                      alpha=0.7, linewidth=1.5,
                      label=f'Control yr {intervention_time}')
        ax.set_xlabel('Time (years)', fontsize=11)
        ax.set_ylabel('Average Fitness', fontsize=11)
        ax.set_title('Population Average Fitness\n(Dynamic payoffs)', fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

        h_label = f' (h={harvest_rate:.2f})' if harvest_rate else ''
        fig.suptitle(f'Hybrid Model: EGT + Extended L-V\n'
                    f'Baseline vs Managed{h_label}',
                    fontsize=13, fontweight='bold', y=1.01)
        plt.tight_layout()
        plt.show()


# ============================================================================
# PART 4: CONSERVATION SCENARIO ANALYSIS
# ============================================================================

def analyze_conservation_scenarios(hybrid_model):
    """
    Runs each conservation scenario through the CEPPM (hybrid model) so that
    EGT strategy evolution and L-V population dynamics are fully coupled via
    dynamic payoff feedback — not computed independently.

    Each scenario simulates T_MAX years with:
      - Natural (unmanaged) dynamics for t < INTERVENTION_TIME
      - Predator control at the scenario harvest rate for t >= INTERVENTION_TIME

    Results report final-year values of x (open foraging frequency),
    K (kiwi population), and S (stoat population).
    """
    print("\n" + "="*70)
    print("CONSERVATION SCENARIO ANALYSIS (CEPPM Hybrid Model)")
    print("="*70)
    print(f"  Simulation: {T_MAX} years, intervention at year {INTERVENTION_TIME}")
    print(f"  All scenarios use full EGT-L-V coupling via dynamic payoff feedback")

    # Scenario definitions — updated regime structure based on nullcline analysis:
    #   h_crit = 0.25 : non-kiwi stoat equilibrium collapses
    #   h_erad ≈ 0.32 : true stoat eradication (stoats sustained by kiwi bonus
    #                   between h_crit and h_erad)
    #   h_erad_theo = 0.60 : theoretical upper bound (PF2050)
    scenarios = {
        'baseline': {
            'description': 'No intervention (h=0)',
            'harvest_rate': 0,
            'int_yr_override': None,
        },
        'scenario_1': {
            'description': 'Scenario 1 — h=0.10, yr 20 (failed management)',
            'harvest_rate': 0.10,
            'int_yr_override': 20,
        },
        'scenario_2a': {
            'description': 'Scenario 2a — h=0.20, yr 20 (partial recovery, below h_crit)',
            'harvest_rate': 0.20,
            'int_yr_override': 20,
        },
        'scenario_2b': {
            'description': 'Scenario 2b — h=0.25, yr 20 (h_crit; kiwi bonus sustains stoats)',
            'harvest_rate': 0.25,
            'int_yr_override': 20,
        },
        'scenario_2c': {
            'description': 'Scenario 2c — h=0.30, yr 20 (kiwi bonus zone; h_crit < h < h_erad)',
            'harvest_rate': 0.30,
            'int_yr_override': 20,
        },
        'scenario_3a': {
            'description': 'Scenario 3a — h=0.40, yr 10 (full suppression, above h_erad)',
            'harvest_rate': 0.40,
            'int_yr_override': 10,
        },
        'scenario_3b': {
            'description': 'Scenario 3b — h=0.60, yr 2 (intensive/PF2050)',
            'harvest_rate': 0.60,
            'int_yr_override': 2,
        },
        'user_defined': {
            'description': f'User-defined — h={HARVEST_RATE:.2f}',
            'harvest_rate': HARVEST_RATE,
            'int_yr_override': None,
        },
    }

    results = {}
    for name, params in scenarios.items():
        h      = params['harvest_rate']
        int_yr = params.get('int_yr_override') or INTERVENTION_TIME
        print(f"\n{name.upper().replace('_', ' ')}: {params['description']}")

        t, x, K, S = hybrid_model.simulate_hybrid_dynamics(
            [X0, K0, S0], T_MAX,
            intervention_time=int_yr,
            harvest_rate=h
        )

        x_final = float(x[-1])
        K_final = float(K[-1])
        S_final = float(S[-1])
        # Average payoff from dynamic (stoat-adjusted) payoffs at final state
        dp = hybrid_model.dynamic_payoffs(S_final)
        tmp = KiwiEGTModel(dp)
        avg_fitness = tmp.average_payoff(x_final) if tmp.find_equilibrium() else 0

        results[name] = {
            'description':       params['description'],
            'harvest_rate':      h,
            'strategy_final':    x_final,
            'kiwi_final':        K_final,
            'stoat_final':       S_final,
            'average_fitness':   avg_fitness,
            't': t, 'x': x, 'K': K, 'S': S,
        }
        print(f"  Final year {T_MAX}: x={x_final:.3f} ({x_final*100:.1f}% open), "
              f"K={K_final:.1f}, S={S_final:.3f}, avg_fitness={avg_fitness:.3f}")

    _plot_scenario_comparison(results)
    return results


def _plot_scenario_comparison(results):
    scenarios  = list(results.keys())
    short_labels = {
        'baseline':     'No\nintervention\n(h=0)',
        'scenario_1':   'Scenario 1\n(h=0.10)\nFailed mgmt',
        'scenario_2a':  'Scenario 2a\n(h=0.20)\nPartial rec.',
        'scenario_2b':  'Scenario 2b\n(h=0.25)\nh_crit',
        'scenario_2c':  'Scenario 2c\n(h=0.30)\nKiwi bonus',
        'scenario_3a':  'Scenario 3a\n(h=0.40)\nFull suppr.',
        'scenario_3b':  'Scenario 3b\n(h=0.60)\nPF2050',
        'user_defined': f'User defined\n(h={HARVEST_RATE:.2f})',
    }
    labels   = [short_labels.get(s, s) for s in scenarios]
    h_crit   = R_STOAT - 0.35
    f_Kmax   = 0.044*150/(1+0.044*0.1*150)
    h_erad   = h_crit + 0.0175*f_Kmax     # ≈ 0.320
    S_floor  = S_MAX*(1-0.35/R_STOAT)

    fig, axes = plt.subplots(1, 3, figsize=(17, 7))

    def bar(ax, vals, color, ylabel, title, ylim=None, hlines=None):
        bars = ax.bar(range(len(scenarios)), vals, alpha=0.75, color=color)
        for s, b in zip(scenarios, bars):
            hr = results[s]['harvest_rate']
            if 0 < hr <= h_crit:
                b.set_color('salmon');     b.set_alpha(0.6)   # below h_crit
            elif h_crit < hr <= h_erad:
                b.set_color('gold');       b.set_alpha(0.7)   # kiwi bonus zone
        ax.set_xticks(range(len(scenarios)))
        ax.set_xticklabels(labels, rotation=0, fontsize=8, ha='center',
                           linespacing=1.3)
        ax.set_ylabel(ylabel, fontsize=11)
        ax.set_title(title, fontsize=12)
        if ylim:
            ax.set_ylim(ylim)
        if hlines:
            for y, col, ls, lbl in hlines:
                ax.axhline(y=y, color=col, linestyle=ls, alpha=0.65,
                          linewidth=1.5, label=lbl)
            ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3, axis='y')

    bar(axes[0],
        [results[s]['strategy_final'] for s in scenarios],
        'steelblue',
        'Open foraging frequency (x)',
        'Open foraging strategy',
        ylim=(0, 1))

    bar(axes[1],
        [results[s]['kiwi_final'] for s in scenarios],
        'forestgreen',
        f'Kiwi population at year {T_MAX}',
        'Kiwi population outcome',
        hlines=[(K0, 'red', '--', f'Initial K0={K0}')])

    bar(axes[2],
        [results[s]['stoat_final'] for s in scenarios],
        'tomato',
        f'Stoat population at year {T_MAX}',
        'Stoat population outcome',
        hlines=[(S_floor, 'darkred', ':', f'S_floor={S_floor:.2f}')])

    fig.suptitle(
        f'CEPPM Conservation Scenario Comparison — Six Scenarios\n'
        f'(T={T_MAX} yrs | salmon=below h_crit={h_crit:.2f} | '
        f'gold=kiwi bonus zone h_crit to h_erad={h_erad:.3f})',
        fontsize=12, fontweight='bold'
    )
    plt.tight_layout()
    plt.show()


# ============================================================================
# PART 5: PAYOFF MATRIX SENSITIVITY ANALYSIS
# ============================================================================

def payoff_sensitivity_analysis_full():
    print("\n" + "="*70)
    print("PAYOFF MATRIX SENSITIVITY ANALYSIS")
    print("="*70)

    # All scenarios proportionally scaled from old values using
    # element-wise scale factors [[1.167, 0.917], [1.25, 1.0]]
    # derived from new_baseline / old_baseline.
    # d=0.22 (minimum viable survival) held fixed across all scenarios.
    # risk_seeking produces a corner solution (x=1.0) in both old and new
    # versions — this is expected behaviour for a strongly open-dominant matrix.
    scenarios = {
        'conservative': np.array([[0.292, 0.321], [0.375, 0.22]]),
        'moderate':     np.array([[0.35,  0.55 ], [0.50,  0.22]]),  # = new baseline
        'extreme':      np.array([[0.233, 0.733], [0.625, 0.22]]),
        'risk_averse':  np.array([[0.292, 0.413], [0.50,  0.22]]),
        'risk_seeking': np.array([[0.408, 0.596], [0.375, 0.22]])
    }

    results = {}
    for name, payoffs in scenarios.items():
        model = KiwiEGTModel(payoffs)
        eq    = model.find_equilibrium()
        if eq is None or not 0 <= eq <= 1:
            results[name] = None; continue
        stability   = model.stability_analysis(eq)
        avg_fitness = model.average_payoff(eq)
        # Intervention effect proportionally scaled from old [[0.10,0.30],[0.05,0.02]]
        new_payoffs = payoffs + np.array([[0.117, 0.275], [0.062, 0.02]])
        m2          = KiwiEGTModel(new_payoffs)
        eq2         = m2.find_equilibrium()
        sc          = eq2 - eq if eq2 and 0 <= eq2 <= 1 else None
        fc          = m2.average_payoff(eq2) - avg_fitness if sc is not None else None
        results[name] = {
            'payoffs': payoffs, 'equilibrium': eq, 'stability': stability,
            'avg_fitness': avg_fitness, 'strategy_change': sc, 'fitness_change': fc
        }
        print(f"\n{name.upper()}: eq={eq:.3f} [{stability}], fitness={avg_fitness:.3f}")
        if sc is not None:
            print(f"  After intervention: shift={sc:+.3f}, Δfitness={fc:+.3f}")

    valid = {k: v for k, v in results.items() if v}
    if valid:
        eqs = [v['equilibrium'] for v in valid.values()]
        cv  = np.std(eqs) / np.mean(eqs) * 100
        print(f"\nCV across scenarios: {cv:.1f}% — "
              f"{'ROBUST' if cv<20 else 'MODERATE' if cv<40 else 'SENSITIVE'}")
    return results


# ============================================================================
# PART 6: L-V PARAMETER SENSITIVITY ANALYSIS
# ============================================================================

def sensitivity_analysis(lv_model):
    print("\n" + "="*70)
    print("SENSITIVITY ANALYSIS")
    print("="*70)
    print("  Note: boundary regions (no coexistence) are shown as gaps/shading.")
    print("  These are biologically meaningful limits, not model errors.\n")

    base = {'r': lv_model.r, 'alpha': lv_model.alpha,
            'beta': lv_model.beta, 'delta': lv_model.delta}
    ranges = {
        'r':     np.linspace(0.1,  0.5,  30),
        'alpha': np.linspace(0.01, 0.1,  30),
        'beta':  np.linspace(0.005,0.05, 30),
        'delta': np.linspace(0.2,  0.6,  30)
    }

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()
    results = {}

    for idx, (param, vals) in enumerate(ranges.items()):
        k_eqs        = []
        n_boundary   = 0

        for v in vals:
            p = base.copy(); p[param] = v
            m = KiwiLotkaVolterraModel(**p, K_max=lv_model.K_max, h=lv_model.h,
                                       r_stoat=lv_model.r_stoat, S_max=lv_model.S_max)
            # suppress_warnings=True: boundary conditions are expected in a sweep
            K_eq, _ = m.find_equilibrium(0, suppress_warnings=True)

            if K_eq >= lv_model.K_max * 0.99:
                # Boundary: no coexistence — kiwi decline to extinction
                k_eqs.append(np.nan)
                n_boundary += 1
            else:
                k_eqs.append(K_eq)
        results[param] = {'values': vals, 'kiwi_equilibria': k_eqs,
                         'n_boundary': n_boundary}

        # Sensitivity coefficient at baseline (skip if baseline is at boundary)
        bi = np.argmin(np.abs(vals - base[param]))
        if 0 < bi < len(k_eqs) - 1:
            k_lo, k_hi, k_c = k_eqs[bi-1], k_eqs[bi+1], k_eqs[bi]
            if not any(np.isnan(v) for v in [k_lo, k_hi, k_c]) and k_c > 0:
                s = ((k_hi - k_lo) / k_c) / ((vals[bi+1] - vals[bi-1]) / base[param])
                print(f"  {param}: 1% change → {s:.2f}% change in K*")
            else:
                print(f"  {param}: baseline is at boundary — sensitivity not defined")

        if n_boundary > 0:
            pct = n_boundary / len(vals) * 100
            print(f"  {param}: {n_boundary}/{len(vals)} ({pct:.0f}%) values outside "
                  f"coexistence regime (delta >= r_stoat boundary)")

        # Plot with boundary shading
        ax = axes[idx]
        ax.plot(vals, k_eqs, 'b-', linewidth=2)
        ax.axvline(x=base[param], color='red', linestyle='--',
                  alpha=0.7, linewidth=2, label='Baseline')
        boundary_vals = [v for v, k in zip(vals, k_eqs) if np.isnan(k)]
        if boundary_vals:
            ax.axvspan(min(boundary_vals), max(boundary_vals),
                      alpha=0.12, color='red',
                      label=f'No coexistence ({n_boundary} values)')
        ax.set_xlabel(param, fontsize=11)
        ax.set_ylabel('Kiwi Equilibrium K*', fontsize=11)
        ax.set_title(f'Sensitivity to {param}', fontsize=12)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

    plt.suptitle('L-V Parameter Sensitivity Analysis\n'
                'Red shading = no coexistence equilibrium (parameter boundary)',
                fontsize=12)
    plt.tight_layout()
    plt.show()
    return results


# ============================================================================
# PART 7: FIELD DATA ANALYSIS
# ============================================================================

def analyze_field_data():
    print("\n" + "="*70)
    print("FIELD DATA ANALYSIS (simulated)")
    print("="*70)
    np.random.seed(42)
    n = 120
    strategies = np.random.choice([0, 1], n, p=[0.65, 0.35])
    fitness    = [max(0, np.random.normal(1.7 if s else 1.3, 0.4 if s else 0.3))
                 for s in strategies]
    years      = np.arange(0, min(T_MAX, 20))  # field observation window (capped at 20 yrs)
    kiwi_c     = K0 + 5*np.sin(years*0.5) + np.random.normal(0, 2, len(years))
    stoat_c    = S0 + 2*np.cos(years*0.5) + np.random.normal(0, 0.5, len(years))

    data    = pd.DataFrame({'strategy': strategies, 'fitness': fitness})
    pop_data = pd.DataFrame({'year': years, 'kiwi': kiwi_c, 'stoats': stoat_c})

    from scipy.stats import ttest_ind
    t_s, p_v = ttest_ind(data[data['strategy']==1]['fitness'],
                         data[data['strategy']==0]['fitness'])
    print(data.groupby('strategy')['fitness'].agg(['count','mean','std']).round(3))
    print(f"\nT-test: t={t_s:.3f}, p={p_v:.4f} ({'significant' if p_v<0.05 else 'not significant'})")

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes[0,0].hist(data[data['strategy']==0]['fitness'], bins=15, alpha=0.7, label='Cover')
    axes[0,0].hist(data[data['strategy']==1]['fitness'], bins=15, alpha=0.7, label='Open')
    axes[0,0].set_title('Fitness Distribution'); axes[0,0].legend()
    data.boxplot('fitness', by='strategy', ax=axes[0,1])
    axes[0,1].set_title('Fitness by Strategy')
    axes[1,0].plot(pop_data['year'], pop_data['kiwi'],  'go-', label='Kiwi')
    axes[1,0].plot(pop_data['year'], pop_data['stoats'], 'ro-', label='Stoats')
    axes[1,0].set_title('Population Time Series'); axes[1,0].legend()
    axes[1,1].plot(pop_data['kiwi'], pop_data['stoats'], 'bo-')
    axes[1,1].set_title('Phase Plot')
    plt.tight_layout(); plt.show()
    return data, pop_data


# ============================================================================
# PART 7B: FORAGING STRATEGY VS HARVEST RATE — FOUR-ZONE SWEEP
# ============================================================================

def plot_foraging_vs_harvest_rate(hybrid_model, intervention_year=5, t_max=None):
    """
    Sweeps stoat harvest rate h from 0 to 0.72 and plots equilibrium open
    foraging proportion x at t_max as a continuous curve.

    Updated with corrected four-zone regime shading based on nullcline analysis:
      Zone 1 (red):    h < h_eff ≈ 0.16        — failed management
      Zone 2 (orange): h_eff to h_crit = 0.25  — partial recovery
      Zone 3 (yellow): h_crit to h_erad ≈ 0.32 — kiwi bonus zone
                       stoats persist through kiwi predation bonus despite
                       non-kiwi equilibrium collapse
      Zone 4 (green):  h_erad to h_erad_theo   — full suppression
      Zone 5 (blue):   h ≥ h_erad_theo = 0.60  — PF2050/eradication

    Parameters
    ----------
    hybrid_model      : KiwiHybridModel instance (already initialised)
    intervention_year : int, year at which harvest begins (default 5)
    t_max             : int, simulation duration (defaults to module T_MAX)
    """
    if t_max is None:
        t_max = T_MAX

    # Derived thresholds
    H_CRIT      = R_STOAT - 0.35
    H_ERAD_THEO = R_STOAT
    H_EFF       = 0.16
    f_Kmax      = 0.044*150/(1+0.044*0.1*150)
    H_ERAD_TRUE = H_CRIT + 0.0175*f_Kmax        # ≈ 0.320

    a_p, b_p = hybrid_model.base_payoffs[0]
    c_p, d_p = hybrid_model.base_payoffs[1]
    denom    = (a_p-b_p)+(d_p-c_p)
    x_star   = float(np.clip((d_p-b_p)/denom, 0, 1)) if abs(denom)>1e-10 else 0.5

    print("\n" + "="*70)
    print("FORAGING STRATEGY vs HARVEST RATE SWEEP (four-zone)")
    print(f"  Intervention year={intervention_year},  t_max={t_max}")
    print(f"  h_crit={H_CRIT:.3f}  h_erad={H_ERAD_TRUE:.4f}  "
          f"h_erad_theo={H_ERAD_THEO:.2f}")
    print("="*70)

    h_vals = np.linspace(0.0, 0.72, 120)
    x_eq   = []
    for hv in h_vals:
        try:
            t_s, x_s, _, _ = hybrid_model.simulate_hybrid_dynamics(
                [X0, K0, S0], t_max,
                intervention_time=intervention_year,
                harvest_rate=hv
            )
            x_eq.append(float(x_s[-1])*100)
        except Exception:
            x_eq.append(np.nan)

    print(f"  Sweep complete. x range: "
          f"{np.nanmin(x_eq):.1f}% – {np.nanmax(x_eq):.1f}%")

    # ── Plot ─────────────────────────────────────────────────────────────
    import matplotlib.patches as mpatches
    fig, ax = plt.subplots(figsize=(11, 6))

    zones = [
        (0,           H_EFF,       '#d62728', 0.12),
        (H_EFF,       H_CRIT,      '#ff7f0e', 0.12),
        (H_CRIT,      H_ERAD_TRUE, '#f5c518', 0.18),
        (H_ERAD_TRUE, H_ERAD_THEO, '#2ca02c', 0.12),
        (H_ERAD_THEO, 0.73,        '#1f77b4', 0.12),
    ]
    for x0z, x1z, col, alph in zones:
        ax.axvspan(x0z, x1z, alpha=alph, color=col)

    for xv, col, lbl in [
        (H_EFF,       '#d62728', f'h≈{H_EFF}  effective recovery threshold'),
        (H_CRIT,      '#ff7f0e', f'h_crit={H_CRIT:.2f}  non-kiwi eq. collapses'),
        (H_ERAD_TRUE, '#b8860b', f'h_erad≈{H_ERAD_TRUE:.3f}  true eradication threshold'),
        (H_ERAD_THEO, '#1f77b4', f'h_erad_theo={H_ERAD_THEO:.2f}  PF2050 upper bound'),
    ]:
        ax.axvline(xv, color=col, linestyle='--', linewidth=1.5, alpha=0.9)

    ax.axhline(x_star*100, color='#555', linestyle=':',  linewidth=1.2,
               label=f'Analytical ESS x*={x_star*100:.2f}%')
    ax.axhline(66.28,      color='#555', linestyle='-.', linewidth=1.2,
               label='Simulated dynamic ESS ≈66.3%')
    ax.axhline(X0*100,     color='black', linestyle=':', linewidth=1.0,
               alpha=0.45, label=f'Initial x₀={X0*100:.0f}%')

    ax.plot(h_vals, x_eq, color='#111', linewidth=2.4, zorder=6,
            label='CEPPM equilibrium x(h)')

    for xc, lbl in [
        (H_EFF/2,                     'Failed\nmanagement'),
        ((H_EFF+H_CRIT)/2,            'Partial\nrecovery'),
        ((H_CRIT+H_ERAD_TRUE)/2,      'Kiwi bonus\nzone'),
        ((H_ERAD_TRUE+H_ERAD_THEO)/2, 'Full\nsuppression'),
        ((H_ERAD_THEO+0.73)/2,        'PF2050\nzone'),
    ]:
        ax.text(xc, 84, lbl, ha='center', va='top', fontsize=8,
                color='#333', style='italic', linespacing=1.3)

    ax.set_xlabel('Stoat harvest rate  h  (annual proportion removed)', fontsize=12)
    ax.set_ylabel('Open foraging proportion at t=200  (%)', fontsize=12)
    ax.set_title(
        f'CEPPM — Equilibrium foraging strategy vs harvest rate\n'
        f'Intervention yr={intervention_year}  t={t_max}  '
        f'K₀={K0}  S₀={S0}  x₀={X0*100:.0f}%  |  '
        f'h_crit={H_CRIT:.2f}  h_erad={H_ERAD_TRUE:.3f}  '
        f'PI_BAR_ESS={hybrid_model.egt_model.average_payoff(x_star):.4f}',
        fontsize=10
    )
    ax.set_xlim(0, 0.72); ax.set_ylim(0, 90)
    ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v,_: f'{v:.2f}'))

    legend_els = [
        plt.Line2D([0],[0], color='#111', lw=2.2, label='CEPPM equilibrium x(h)'),
        plt.Line2D([0],[0], color='#555', ls=':', lw=1.2,
                   label=f'Analytical ESS x*={x_star*100:.2f}%'),
        plt.Line2D([0],[0], color='#555', ls='-.', lw=1.2,
                   label='Simulated ESS ≈66.3%'),
        plt.Line2D([0],[0], color='black', ls=':', lw=1.0, alpha=0.5,
                   label=f'Initial x₀={X0*100:.0f}%'),
        plt.Line2D([0],[0], color='#d62728', ls='--', lw=1.5,
                   label=f'h≈{H_EFF} effective recovery threshold'),
        plt.Line2D([0],[0], color='#ff7f0e', ls='--', lw=1.5,
                   label=f'h_crit={H_CRIT:.2f} non-kiwi eq. collapses'),
        plt.Line2D([0],[0], color='#b8860b', ls='--', lw=1.5,
                   label=f'h_erad≈{H_ERAD_TRUE:.3f} true eradication threshold'),
        plt.Line2D([0],[0], color='#1f77b4', ls='--', lw=1.5,
                   label=f'h_erad_theo={H_ERAD_THEO:.2f} PF2050 upper bound'),
        mpatches.Patch(color='#d62728', alpha=0.25, label='Failed management zone'),
        mpatches.Patch(color='#ff7f0e', alpha=0.25, label='Partial recovery zone'),
        mpatches.Patch(color='#f5c518', alpha=0.35, label='Kiwi bonus zone'),
        mpatches.Patch(color='#2ca02c', alpha=0.25, label='Full suppression zone'),
        mpatches.Patch(color='#1f77b4', alpha=0.25, label='PF2050 / eradication zone'),
    ]
    ax.legend(handles=legend_els, fontsize=7.5, loc='lower right',
              framealpha=0.92, ncol=2)
    ax.grid(True, alpha=0.20)
    plt.tight_layout()
    plt.show()

    print(f"\n  Key values from sweep:")
    for hv_check, label in [
        (0.00, 'h=0.00 (unmanaged)'),
        (H_EFF,       f'h≈{H_EFF} (eff. recovery threshold)'),
        (H_CRIT,      f'h_crit={H_CRIT:.2f}'),
        (H_ERAD_TRUE, f'h_erad≈{H_ERAD_TRUE:.3f}'),
        (H_ERAD_THEO, f'h_erad_theo={H_ERAD_THEO:.2f}'),
    ]:
        idx = int(np.argmin(np.abs(h_vals-hv_check)))
        print(f"    x at {label}: {x_eq[idx]:.1f}%")

    return h_vals, np.array(x_eq)


# ============================================================================
# PART 7C: THREE-MODEL COMPARISON
# ============================================================================

def three_model_comparison(hybrid_model, t_max=None):
    """
    Compares three models across five scenarios:
      1. Standalone EGT — strategy evolution only, base payoffs, no population
         dynamics. Scenario-blind: converges to x*=68.75% regardless of h.
      2. Standalone L-V — population dynamics only, strategy fixed at x=X0.
         Behaviourally static: misses post-intervention strategy shift.
      3. CEPPM (coupled) — full bidirectional coupling via dynamic payoffs
         and strategy-dependent L-V parameters.

    Updated scenarios (h=0.30 replaces h=0.60 to illustrate kiwi bonus zone):
      Control     h=0.00  no intervention
      Scenario 1  h=0.10  yr 20  failed management
      Scenario 2a h=0.20  yr 20  partial recovery
      Scenario 2c h=0.30  yr 20  kiwi bonus zone (NEW)
      Scenario 3a h=0.40  yr 10  full suppression
    """
    if t_max is None:
        t_max = T_MAX

    H_CRIT      = R_STOAT - 0.35
    f_Kmax      = 0.044*150/(1+0.044*0.1*150)
    H_ERAD_TRUE = H_CRIT + 0.0175*f_Kmax
    S_FLOOR_VAL = S_MAX*(1-0.35/R_STOAT)
    SIM_ESS     = 66.28

    bp = hybrid_model.base_payoffs
    a_p,b_p = bp[0]; c_p,d_p = bp[1]
    denom = (a_p-b_p)+(d_p-c_p)
    x_star = float(np.clip((d_p-b_p)/denom, 0, 1))

    # EGT payoff helper
    def avg_payoff_egt(x):
        piA = x*a_p+(1-x)*b_p
        piB = x*c_p+(1-x)*d_p
        return x*piA+(1-x)*piB
    PI_BAR = avg_payoff_egt(x_star)

    print("\n" + "="*70)
    print("THREE-MODEL COMPARISON (EGT | L-V | CEPPM)")
    print(f"  Scenarios: Control, 1(h=0.10), 2a(h=0.20), 2c(h=0.30), 3a(h=0.40)")
    print(f"  h_crit={H_CRIT:.3f}  h_erad={H_ERAD_TRUE:.4f}  S_floor={S_FLOOR_VAL:.3f}")
    print("="*70)

    scenarios_3m = [
        ('Control\n(h=0)',              0.00, T_MAX-1, 'Baseline'),
        ('Scenario 1\nh=0.10\n(yr 20)', 0.10, 20,     'Failed management'),
        ('Scenario 2a\nh=0.20\n(yr 20)',0.20, 20,     'Partial recovery'),
        ('Scenario 2c\nh=0.30\n(yr 20)',0.30, 20,     'Kiwi bonus zone'),
        ('Scenario 3a\nh=0.40\n(yr 10)',0.40, 10,     'Full suppression'),
    ]

    def run_egt_standalone(t_mx, n_pts=500):
        def odes(t, y):
            x = np.clip(y[0], 0.01, 0.99)
            piA = x*bp[0,0]+(1-x)*bp[0,1]
            piB = x*bp[1,0]+(1-x)*bp[1,1]
            return [x*(piA-(x*piA+(1-x)*piB))]
        sol = solve_ivp(odes, [0,t_mx], [X0],
                        t_eval=np.linspace(0,t_mx,n_pts),
                        method='RK45', rtol=1e-7, atol=1e-9)
        return sol.t, sol.y[0]*100

    def run_lv_standalone(h, int_yr, t_mx, n_pts=500):
        r_eff  = 0.05*(avg_payoff_egt(X0)/PI_BAR)
        al_eff = 0.044*(X0*1.3+(1-X0)*0.7)
        def fK(K): return al_eff*K/(1+al_eff*0.1*K)
        def floor_nat(S, fKv):
            nat = R_STOAT*S*(1-S/S_MAX)+0.0175*fKv*S-0.35*S
            nk  = R_STOAT*S*(1-S/S_MAX)-0.35*S
            if S<=S_FLOOR_VAL and nk<0: nat=max(nat,0.)
            return nat
        def odes(t, y, hv):
            K,S = max(y[0],0.), max(y[1],0.)
            return [r_eff*K*(1-K/150)-fK(K)*S,
                    floor_nat(S,fK(K))-hv*S]
        ic = [K0, S0]
        n1 = max(2, int(n_pts*int_yr/t_mx))
        s1 = solve_ivp(lambda t,y: odes(t,y,0), [0,int_yr], ic,
                       t_eval=np.linspace(0,int_yr,n1),
                       method='RK45', rtol=1e-7, atol=1e-9)
        ic2 = [float(s1.y[i,-1]) for i in range(2)]
        n2  = max(2, n_pts-n1)
        s2  = solve_ivp(lambda t,y: odes(t,y,h), [int_yr,t_mx], ic2,
                        t_eval=np.linspace(int_yr,t_mx,n2),
                        method='RK45', rtol=1e-7, atol=1e-9)
        t  = np.concatenate([s1.t, s2.t])
        K_ = np.concatenate([s1.y[0], s2.y[0]])
        S_ = np.concatenate([s1.y[1], s2.y[1]])
        return t, np.full(len(t), X0*100), K_, S_

    all_res = {}
    for lbl, h, iy, regime in scenarios_3m:
        print(f"  Running {lbl.replace(chr(10),' ')} ...")
        t_e, x_e          = run_egt_standalone(t_max)
        t_l, xl, Kl, Sl   = run_lv_standalone(h, iy, t_max)
        t_c, xc, Kc, Sc   = hybrid_model.simulate_hybrid_dynamics(
            [X0,K0,S0], t_max,
            intervention_time=iy, harvest_rate=h)
        xc = np.array(xc)*100
        all_res[lbl] = dict(h=h, iy=iy, regime=regime,
                            egt=(t_e,x_e), lv=(t_l,xl,Kl,Sl),
                            ceppm=(t_c,xc,Kc,Sc))
        print(f"    EGT→{x_e[-1]:.1f}%  L-V K={Kl[-1]:.1f} S={Sl[-1]:.3f}"
              f"  CEPPM x={xc[-1]:.1f}% K={Kc[-1]:.1f} S={Sc[-1]:.3f}")

    EGT_C='#1f77b4'; LV_C='#2ca02c'; CEPPM_C='#d62728'
    n_sc = len(scenarios_3m)
    fig  = plt.figure(figsize=(15, 4.2*n_sc))
    fig.suptitle(
        'Three-model comparison: EGT only | L-V only | CEPPM (coupled)\n'
        f'h_crit={H_CRIT:.2f}  h_erad={H_ERAD_TRUE:.3f}  '
        f'S_floor={S_FLOOR_VAL:.3f}  x*={x_star*100:.2f}%  '
        f'Sim ESS={SIM_ESS}%',
        fontsize=11, y=1.002
    )
    import matplotlib.gridspec as gridspec
    gs = gridspec.GridSpec(n_sc, 3, figure=fig, hspace=0.55, wspace=0.30)

    for row, (lbl, h, iy, regime) in enumerate(scenarios_3m):
        r    = all_res[lbl]
        t_e, x_e          = r['egt']
        t_l, xl, Kl, Sl   = r['lv']
        t_c, xc, Kc, Sc   = r['ceppm']

        ax_x = fig.add_subplot(gs[row,0])
        ax_K = fig.add_subplot(gs[row,1])
        ax_S = fig.add_subplot(gs[row,2])

        # Strategy
        ax_x.plot(t_e, x_e, color=EGT_C,   lw=1.8, ls='--',
                  label=f'EGT only →{x_e[-1]:.1f}%')
        ax_x.plot(t_l, xl,  color=LV_C,    lw=1.8, ls=':',
                  label=f'L-V only (fixed {X0*100:.0f}%)')
        ax_x.plot(t_c, xc,  color=CEPPM_C, lw=2.2,
                  label=f'CEPPM →{xc[-1]:.1f}%')
        ax_x.axhline(x_star*100, color='#888', lw=1.0, ls=':',
                     label=f'ESS {x_star*100:.1f}%')
        ax_x.axhline(SIM_ESS,   color='#888', lw=1.0, ls='-.',
                     label=f'Sim ESS {SIM_ESS}%')
        if iy < t_max:
            ax_x.axvline(iy, color='#aaa', lw=1.0, ls=':', alpha=0.7)
        ax_x.set_xlim(0,t_max); ax_x.set_ylim(0,90)
        ax_x.set_ylabel('Open foraging (%)', fontsize=9)
        ax_x.set_xlabel('Time (years)', fontsize=9)
        ax_x.set_title(
            f'{lbl.replace(chr(10)," ")} — {regime}\nStrategy x(t)',
            fontsize=9)
        ax_x.legend(fontsize=7.0, loc='upper left', framealpha=0.9)
        ax_x.grid(True, alpha=0.18)

        # Kiwi
        ax_K.plot(t_l, Kl, color=LV_C,    lw=1.8, ls=':', label=f'L-V →{Kl[-1]:.1f}')
        ax_K.plot(t_c, Kc, color=CEPPM_C, lw=2.2, label=f'CEPPM →{Kc[-1]:.1f}')
        ax_K.axhline(150, color='#444', lw=1.0, ls='--', alpha=0.7, label='K_max=150')
        ax_K.axhline(K0,  color='#999', lw=1.0, ls=':',  alpha=0.7, label=f'K₀={K0}')
        if iy < t_max:
            ax_K.axvline(iy, color='#aaa', lw=1.0, ls=':', alpha=0.7)
        ax_K.set_xlim(0,t_max); ax_K.set_ylim(0,165)
        ax_K.set_ylabel('Kiwi (birds / 1,000 ha)', fontsize=9)
        ax_K.set_xlabel('Time (years)', fontsize=9)
        ax_K.set_title('Kiwi K(t)', fontsize=9)
        ax_K.legend(fontsize=7.5, loc='upper left', framealpha=0.9)
        ax_K.grid(True, alpha=0.18)

        # Stoat
        ax_S.plot(t_l, Sl, color=LV_C,    lw=1.8, ls=':', label=f'L-V →{Sl[-1]:.3f}')
        ax_S.plot(t_c, Sc, color=CEPPM_C, lw=2.2, label=f'CEPPM →{Sc[-1]:.3f}')
        ax_S.axhline(S_FLOOR_VAL, color='#639922', lw=1.2, ls='--',
                     alpha=0.85, label=f'S_floor={S_FLOOR_VAL:.3f}')
        if iy < t_max:
            ax_S.axvline(iy, color='#aaa', lw=1.0, ls=':', alpha=0.7,
                         label=f'Intervention yr {iy}')
        ax_S.set_xlim(0,t_max); ax_S.set_ylim(-0.05, 4.2)
        ax_S.set_ylabel('Stoat (stoats / 1,000 ha)', fontsize=9)
        ax_S.set_xlabel('Time (years)', fontsize=9)
        ax_S.set_title('Stoat S(t)', fontsize=9)
        ax_S.legend(fontsize=7.5, loc='upper right', framealpha=0.9)
        ax_S.grid(True, alpha=0.18)

    plt.savefig('three_model_comparison.png', dpi=160, bbox_inches='tight')
    plt.show()
    print("  Saved: three_model_comparison.png")
    return all_res


# ============================================================================
# PART 8: MAIN ANALYSIS PIPELINE
# ============================================================================

def run_complete_kiwi_analysis():

    print("\n" + "="*70)
    print("STEP 1: MODEL INITIALIZATION")
    print("="*70)

    # EGT model
    # EGT model — updated to new baseline payoffs [[0.35,0.55],[0.50,0.22]]
    # Consistent with hybrid model base payoffs (Option C).
    # Proportionally scaled from old baseline [[0.30,0.60],[0.40,0.22]]
    # using element-wise scale factors [[1.167,0.917],[1.25,1.0]].
    # d=0.22 (minimum viable chick survival; DOC Recovery Plan) held fixed.
    kiwi_payoffs = np.array([[0.35, 0.55], [0.50, 0.22]])
    egt_model    = KiwiEGTModel(kiwi_payoffs)
    eq           = egt_model.find_equilibrium()
    stability    = egt_model.stability_analysis(eq)
    print(f"\nEGT equilibrium: {eq:.3f} ({eq*100:.1f}% open) [{stability}]")

    # Extended L-V model
    r, alpha, beta, delta = 0.05, 0.044, 0.0175, 0.35
    K_max, h              = 150, 0.1
    lv_model              = KiwiLotkaVolterraModel(r, alpha, beta, delta,
                                                   K_max=K_max, h=h,
                                                   r_stoat=R_STOAT, S_max=S_MAX)
    print(f"\n  Core parameters:")
    print(f"    r={r}  (kiwi intrinsic growth; DOC Recovery Plan 2018-2028)")
    print(f"    α={alpha} (predation rate; updated — reflects per-capita encounter")
    print(f"           rate consistent with <5% kiwi in stoat diet,")
    print(f"           Murphy & Dowding 1995; King & Powell 2007)")
    print(f"    β={beta} (stoat conversion efficiency; updated — kiwi contribute")
    print(f"           marginally to stoat reproduction; generalist diet)")
    print(f"    δ={delta}  (stoat natural death rate; annual survival=exp(-0.35)={np.exp(-0.35):.2f})")
    print(f"           Represents natural mortality only (disease, starvation, predation)")
    print(f"           NOT including trap mortality — that enters via harvest term h·S")
    print(f"           Source: King (1983); Powell & King (1997); annual survival ~70%")
    print(f"           With delta=0.35: NO coexistence without management — kiwi decline")
    print(f"           to extinction, consistent with observed 2% annual decline without"  )
    print(f"           predator control (McLennan et al. 1996; DOC Recovery Plan 2018)")
    print(f"\n  Extended model parameters:")
    print(f"    K_max={K_max}  (kiwi carrying capacity)")
    print(f"    h={h}      (Holling Type II handling time)")
    print(f"    r_stoat={R_STOAT}  (stoat baseline growth from non-kiwi prey)")
    print(f"    S_max={S_MAX}     (stoat non-kiwi carrying capacity)")

    K_eq, S_eq = lv_model.find_equilibrium()
    S_floor    = S_MAX * (1 - 0.35 / R_STOAT)
    print(f"\n  Coexistence equilibrium (no control): K={K_eq:.1f}, S={S_eq:.3f}")
    print(f"  Stoat floor (non-kiwi prey only):    K=0,  S={S_floor:.3f}")
    print(f"  Initial conditions: K0={K0}, S0={S0}, X0={X0}")

    # Hybrid model — uses SAME K0, S0 as L-V for consistency
    hybrid_model = KiwiHybridModel(egt_model, r, alpha, beta, delta,
                                   K_max=K_max, h=h,
                                   r_stoat=R_STOAT, S_max=S_MAX)

    # ========== STEP 2: VISUALISE ==========
    print("\n" + "="*70)
    print("STEP 2: BASE MODEL VISUALISATION")
    print("="*70)

    egt_model.plot_payoff_functions()
    egt_model.plot_phase_portrait()
    lv_model.plot_holling_response()
    print("\n  Demonstrating generalist stoat persistence behaviour...")
    lv_model.plot_stoat_persistence()   # NEW: shows stoats persist without kiwi
    lv_model.plot_phase_portrait_with_field(PHASE_PORTRAIT_ICS)

    # Baseline (no intervention) — uses config K0, S0
    t_base, K_base, S_base = lv_model.simulate_dynamics([K0, S0], T_MAX)
    lv_model.plot_time_series(t_base, K_base, S_base)

    # ========== STEP 3: CONSERVATION SCENARIOS ==========
    scenario_results = analyze_conservation_scenarios(hybrid_model)

    # ========== STEP 4: INTERVENTION (USER HARVEST RATE) ==========
    print("\n" + "="*70)
    print(f"STEP 4: INTERVENTION SIMULATION (harvest rate = {HARVEST_RATE:.2f})")
    print("="*70)

    t_ctrl, K_ctrl, S_ctrl = lv_model.simulate_dynamics(
        [K0, S0], T_MAX,
        intervention_time=INTERVENTION_TIME,
        harvest_rate=HARVEST_RATE
    )
    lv_model.plot_time_series(t_ctrl, K_ctrl, S_ctrl,
                             intervention_time=INTERVENTION_TIME,
                             harvest_rate=HARVEST_RATE)

    print(f"\nL-V results at year {T_MAX} (intervention at year {INTERVENTION_TIME}, h={HARVEST_RATE:.2f}):")
    print(f"  Kiwi:        {K_ctrl[-1]:.1f}  (no control: {K_base[-1]:.1f},  change: {((K_ctrl[-1]-K_base[-1])/K_base[-1]*100):+.1f}%)")
    print(f"  Stoats:      {S_ctrl[-1]:.3f}  (no control: {S_base[-1]:.3f})")
    S_floor_v = S_MAX * (1 - 0.35 / R_STOAT)
    h_crit_v  = R_STOAT - delta
    f_Kmax_v  = 0.044*150/(1+0.044*0.1*150)
    h_erad_v  = h_crit_v + 0.0175*f_Kmax_v
    if HARVEST_RATE >= R_STOAT:
        print(f"  Stoat regime: THEORETICAL UPPER BOUND "
              f"(h={HARVEST_RATE:.2f} ≥ h_erad_theo={R_STOAT:.2f})")
    elif HARVEST_RATE >= h_erad_v:
        print(f"  Stoat regime: FULL SUPPRESSION — stoats eradicated "
              f"(h={HARVEST_RATE:.2f} ≥ h_erad={h_erad_v:.3f})")
    elif HARVEST_RATE > h_crit_v:
        print(f"  Stoat regime: KIWI BONUS ZONE — stoats persist through kiwi bonus "
              f"(h_crit={h_crit_v:.2f} < h={HARVEST_RATE:.2f} < h_erad={h_erad_v:.3f})")
    else:
        print(f"  Stoat regime: COEXISTENCE / PARTIAL RECOVERY "
              f"(h={HARVEST_RATE:.2f} ≤ h_crit={h_crit_v:.2f})")

    # EGT behavioural response
    int_payoffs = kiwi_payoffs + np.array([[0.117, 0.275], [0.062, 0.02]])
    t_egt, x_egt = egt_model.simulate_dynamics(
        X0, T_MAX, intervention_time=INTERVENTION_TIME, new_payoffs=int_payoffs
    )

    # Find x just before intervention for comparison
    x_pre_intervention = x_egt[np.searchsorted(t_egt, INTERVENTION_TIME) - 1]
    x_final = x_egt[-1]
    x_change = x_final - X0
    x_change_post = x_final - x_pre_intervention

    print(f"\nEGT strategy results:")
    print(f"  Open foraging start:               {X0:.3f}  ({X0*100:.1f}%)")
    print(f"  Open foraging at intervention yr:  {x_pre_intervention:.3f}  ({x_pre_intervention*100:.1f}%)")
    print(f"  Open foraging final (yr {T_MAX}):      {x_final:.3f}  ({x_final*100:.1f}%)")
    print(f"  Change from start:                 {x_change:+.3f}  ({x_change*100:+.1f}pp)")
    print(f"  Change due to intervention:        {x_change_post:+.3f}  ({x_change_post*100:+.1f}pp)")

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(t_egt, x_egt, 'b-', linewidth=2)
    ax.axvline(x=INTERVENTION_TIME, color='green', linestyle='--',
               linewidth=2, label=f'Predator Control starts (yr {INTERVENTION_TIME}, h={HARVEST_RATE:.2f})')
    ax.axhline(y=X0, color='gray', linestyle=':', alpha=0.7,
               label=f'Starting proportion ({X0:.2f})')
    ax.axhline(y=x_final, color='blue', linestyle=':', alpha=0.7,
               label=f'Final proportion ({x_final:.3f}, {x_change*100:+.1f}pp from start)')
    ax.annotate(f'{x_change*100:+.1f}pp\nfrom start',
                xy=(T_MAX*0.85, (X0+x_final)/2),
                fontsize=10, color='blue',
                arrowprops=dict(arrowstyle='->', color='blue'),
                xytext=(T_MAX*0.85, (X0+x_final)/2))
    ax.set_xlabel('Time (years)', fontsize=12)
    ax.set_ylabel('Proportion Open Foraging', fontsize=12)
    ax.set_title('EGT: Behavioural Response to Predator Control\n'
                f'Open foraging {x_change*100:+.1f}pp from start ({X0:.2f} → {x_final:.3f})',
                fontsize=13)
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(0, 1)
    plt.tight_layout()
    plt.show()

    # ========== STEP 5: HYBRID MODEL ==========
    print("\n" + "="*70)
    print("STEP 5: HYBRID MODEL")
    print("="*70)

    # Baseline: no predator control
    print("\nRunning baseline hybrid (no predator control)...")
    t_h, x_h, K_h, S_h = hybrid_model.simulate_hybrid_dynamics(
        [X0, K0, S0], T_MAX
    )

    # Managed: with user harvest rate and intervention time
    print(f"Running managed hybrid (h={HARVEST_RATE:.2f}, intervention yr {INTERVENTION_TIME})...")
    t_hm, x_hm, K_hm, S_hm = hybrid_model.simulate_hybrid_dynamics(
        [X0, K0, S0], T_MAX,
        intervention_time=INTERVENTION_TIME,
        harvest_rate=HARVEST_RATE
    )

    hybrid_model.plot_hybrid_results(
        t_h, x_h, K_h, S_h,
        t_m=t_hm, x_m=x_hm, K_m=K_hm, S_m=S_hm,
        intervention_time=INTERVENTION_TIME,
        harvest_rate=HARVEST_RATE
    )

    x_h_change  = x_h[-1]  - X0
    x_hm_change = x_hm[-1] - X0
    x_hm_post   = x_hm[-1] - x_hm[np.searchsorted(t_hm, INTERVENTION_TIME) - 1]

    print(f"\nHybrid model results at year {T_MAX}:")
    print(f"  {'':30} {'No control':>12} {'With control':>14}")
    print(f"  {'─'*58}")
    print(f"  {'Open foraging start':30} {X0:>12.3f} {X0:>14.3f}")
    print(f"  {'Open foraging final':30} {x_h[-1]:>12.3f} {x_hm[-1]:>14.3f}")
    print(f"  {'Change from start (pp)':30} {x_h_change*100:>+11.1f}% {x_hm_change*100:>+13.1f}%")
    print(f"  {'Post-intervention shift (pp)':30} {'—':>12} {x_hm_post*100:>+13.1f}%")
    print(f"  {'Kiwi population':30} {K_h[-1]:>12.1f} {K_hm[-1]:>14.1f}")
    print(f"  {'Stoat population':30} {S_h[-1]:>12.3f} {S_hm[-1]:>14.3f}")

    # ========== STEP 6-7: SENSITIVITY + FIELD DATA ==========
    sens_results = sensitivity_analysis(lv_model)
    field_data, pop_data = analyze_field_data()

    # ========== STEP 5B: FORAGING vs HARVEST RATE SWEEP ==========
    print("\n" + "="*70)
    print("STEP 5B: FORAGING STRATEGY vs HARVEST RATE — FOUR-ZONE SWEEP")
    print("="*70)
    foraging_sweep_h, foraging_sweep_x = plot_foraging_vs_harvest_rate(
        hybrid_model, intervention_year=5, t_max=T_MAX
    )

    # ========== STEP 5C: THREE-MODEL COMPARISON ==========
    print("\n" + "="*70)
    print("STEP 5C: THREE-MODEL COMPARISON (EGT | L-V | CEPPM)")
    print("="*70)
    three_model_results = three_model_comparison(hybrid_model, t_max=T_MAX)

    # ========== STEP 8: SUMMARY ==========
    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70)
    print(f"\nInitial conditions (all models consistent):")
    print(f"  K0={K0}, S0={S0}, X0={X0} ({X0*100:.0f}% open foraging)")
    print(f"  Intervention year: {INTERVENTION_TIME},  Harvest rate: {HARVEST_RATE:.2f}")
    print(f"\nL-V model outcomes at year {T_MAX}:")
    print(f"  No control:   K={K_base[-1]:.1f}, S={S_base[-1]:.3f}")
    print(f"  With control: K={K_ctrl[-1]:.1f}, S={S_ctrl[-1]:.3f}  ({((K_ctrl[-1]-K_base[-1])/K_base[-1]*100):+.1f}% kiwi change)")
    print(f"\nEGT strategy outcomes at year {T_MAX}:")
    print(f"  Open foraging: {X0:.3f} → {x_final:.3f}  ({(x_final-X0)*100:+.1f}pp change from start)")
    print(f"  Intervention effect: {x_pre_intervention:.3f} → {x_final:.3f}  ({(x_final-x_pre_intervention)*100:+.1f}pp post-intervention shift)")
    print(f"\nHybrid model (no control) at year {T_MAX}:")
    print(f"  Open foraging: {X0:.3f} → {x_h[-1]:.3f}  ({x_h_change*100:+.1f}pp)")
    print(f"Hybrid model (h={HARVEST_RATE:.2f}, intervention yr {INTERVENTION_TIME}) at year {T_MAX}:")
    print(f"  Open foraging: {X0:.3f} → {x_hm[-1]:.3f}  ({x_hm_change*100:+.1f}pp)")
    print(f"  Post-intervention strategy shift: {x_hm_post*100:+.1f}pp")
    print(f"\nGeneralist stoat thresholds (updated — nullcline analysis):")
    S_floor_val  = S_MAX*(1-0.35/R_STOAT)
    h_crit_v     = R_STOAT-delta
    f_Kmax_v     = 0.044*150/(1+0.044*0.1*150)
    h_erad_v     = h_crit_v+0.0175*f_Kmax_v
    print(f"  S_floor={S_floor_val:.3f}  h_crit={h_crit_v:.3f}  "
          f"h_erad={h_erad_v:.4f}  h_erad_theo={R_STOAT:.2f}")
    if HARVEST_RATE >= R_STOAT:
        print(f"  → THEORETICAL ERADICATION REGIME at h={HARVEST_RATE:.2f} "
              f"(h ≥ h_erad_theo={R_STOAT})")
    elif HARVEST_RATE >= h_erad_v:
        print(f"  → FULL SUPPRESSION at h={HARVEST_RATE:.2f} "
              f"(h ≥ h_erad={h_erad_v:.3f})")
    elif HARVEST_RATE > h_crit_v:
        print(f"  → KIWI BONUS ZONE at h={HARVEST_RATE:.2f} "
              f"(h_crit={h_crit_v:.2f} < h < h_erad={h_erad_v:.3f})")
        print(f"     Stoats persist through kiwi predation bonus despite "
              f"non-kiwi equilibrium collapse")
    else:
        print(f"  → COEXISTENCE / PARTIAL RECOVERY at h={HARVEST_RATE:.2f} "
              f"(h ≤ h_crit={h_crit_v:.2f})")
    print(f"\nRemaining limitations:")
    print(f"  • Beech mast not explicitly modelled (r_stoat increases during mast)")
    print(f"  • Spatial reinvasion not modelled — real eradication harder than h > r_stoat")
    print(f"  • r_stoat and S_max need empirical calibration to rodent data")
    print(f"  • EGT intervention payoffs need empirical validation (SS flag)")
    print("\n" + "="*70)
    print("ANALYSIS COMPLETE")
    print("="*70)

    return {
        'egt_model':            egt_model,
        'lv_model':             lv_model,
        'hybrid_model':         hybrid_model,
        'scenario_results':     scenario_results,
        'sensitivity_results':  sens_results,
        'field_data':           field_data,
        'population_data':      pop_data,
        'foraging_sweep_h':     foraging_sweep_h,
        'foraging_sweep_x':     foraging_sweep_x,
        'three_model_results':  three_model_results,
    }


# ============================================================================
# RUN
# ============================================================================

if __name__ == "__main__":
    results = run_complete_kiwi_analysis()
    print("\n✅ Results in 'results' dictionary. All plots displayed.")
